### ISSUE TITLE
Look into removing or simplifying xsltproc requirement

### ISSUE THREAD

**Issue by gbirchmeier** [connamara/quickfixn#104]
All xsltproc does is create a pretty html-ized output for UTs.

It's kind of annoying to install on Windows because of its dependencies.

I think it'd be good if we can either remove it or make it really easy to install.

One possible option: Use Ruby (with or without a gem) to do xsltproc's job.  Since tests are mainly going to be run by people hacking on QF/n, and those developers will already have Ruby, I see no big downside to this (aside from increasing our reliance on Ruby).

**Comment by cbusbey** [comment]
- [ ] remove xslt execution calls
- [ ] remove legacy xslt templates
- [ ] remove reference in readme
