### ISSUE TITLE
Make Field.Tag static const

### ISSUE THREAD

**Issue by nkokarev** [connamara/quickfixn#136]
Now if i want to get a field's Tag (number) i need to instantiate this Field. I think it would be better to have Tag as public static const and then pass it to the base ctor instead of having this value hardcoded  into a base ctor call.

**Comment by gbirchmeier** [comment]
Only took me 8 years, but I finally did it!

**Comment by gbirchmeier** [comment]
Doh, reopening, forgot release notes

**Comment by gbirchmeier** [comment]
Release notes added.
