### ISSUE TITLE
Sequence Numbers are being reset on restart

### ISSUE THREAD

**Issue by jcwild** [connamara/quickfixn#139]
Following on from issue #22, it seems that when the application is restarted, sequence numbers are being reset to 1 rather than continuing from where they were.  The sender sequence number should only be reset to 1 if it is a new day (as determined from the StartTime/EndTime in the config, and only then if the times are distinct)

My message log is as follows:

**\* (connected, happily heartbeating)

20121102-11:36:26.746 : 8=FIX.4.4 | 9=64 | 35=0 | 34=65 | 49=SENDER | 52=20121102-11:36:26.746 | 56=TARGET | 10=245 | 
20121102-11:37:25.804 : 8=FIX.4.4 | 9=64 | 35=0 | 34=66 | 49=TARGET | 52=20121102-11:37:25.776 | 56=SENDER | 10=249 | 
20121102-11:37:26.805 : 8=FIX.4.4 | 9=64 | 35=0 | 34=66 | 49=SENDER | 52=20121102-11:37:26.805 | 56=TARGET | 10=243 | 
20121102-11:38:25.844 : 8=FIX.4.4 | 9=64 | 35=0 | 34=67 | 49=TARGET | 52=20121102-11:38:25.837 | 56=SENDER | 10=249 | 
20121102-11:38:26.863 : 8=FIX.4.4 | 9=64 | 35=0 | 34=67 | 49=SENDER | 52=20121102-11:38:26.845 | 56=TARGET | 10=249 | 

**\* (restarted the application here - sender MsgSeqNum incorrectly set back to 1)

20121102-11:39:05.215 : 8=FIX.4.4 | 9=75 | 35=A | 34=1 | 49=SENDER | 52=20121102-11:39:05.215 | 56=TARGET | 98=0 | 108=60 | 10=225 | 
20121102-11:39:05.244 : 8=FIX.4.4 | 9=114 | 35=5 | 34=68 | 49=TARGET | 52=20121102-11:39:05.216 | 56=SENDER | 58=MsgSeqNum too low, expecting 68 but received 1 | 10=244 | 
20121102-11:39:05.262 : 8=FIX.4.4 | 9=63 | 35=5 | 34=2 | 49=SENDER | 52=20121102-11:39:05.261 | 56=TARGET | 10=184 | 
20121102-11:40:05.268 : 8=FIX.4.4 | 9=75 | 35=A | 34=3 | 49=SENDER | 52=20121102-11:40:05.267 | 56=TARGET | 98=0 | 108=60 | 10=226 | 
20121102-11:40:05.276 : 8=FIX.4.4 | 9=114 | 35=5 | 34=69 | 49=TARGET | 52=20121102-11:40:05.268 | 56=SENDER | 58=MsgSeqNum too low, expecting 68 but received 3 | 10=246 | 
20121102-11:40:05.276 : 8=FIX.4.4 | 9=63 | 35=5 | 34=4 | 49=SENDER | 52=20121102-11:40:05.276 | 56=TARGET | 10=184 | 
20121102-11:41:05.318 : 8=FIX.4.4 | 9=75 | 35=A | 34=5 | 49=SENDER | 52=20121102-11:41:05.318 | 56=TARGET | 98=0 | 108=60 | 10=226 | 
20121102-11:41:05.326 : 8=FIX.4.4 | 9=114 | 35=5 | 34=70 | 49=TARGET | 52=20121102-11:41:05.319 | 56=SENDER | 58=MsgSeqNum too low, expecting 68 but received 5 | 10=238 | 
20121102-11:41:05.327 : 8=FIX.4.4 | 9=63 | 35=5 | 34=6 | 49=SENDER | 52=20121102-11:41:05.327 | 56=TARGET | 10=184 | 
20121102-11:42:05.373 : 8=FIX.4.4 | 9=75 | 35=A | 34=7 | 49=SENDER | 52=20121102-11:42:05.372 | 56=TARGET | 98=0 | 108=60 | 10=229 | 
20121102-11:42:05.395 : 8=FIX.4.4 | 9=114 | 35=5 | 34=71 | 49=TARGET | 52=20121102-11:42:05.373 | 56=SENDER | 58=MsgSeqNum too low, expecting 68 but received 7 | 10=242 | 
20121102-11:42:05.395 : 8=FIX.4.4 | 9=63 | 35=5 | 34=8 | 49=SENDER | 52=20121102-11:42:05.395 | 56=TARGET | 10=192 | 
20121102-11:43:05.427 : 8=FIX.4.4 | 9=75 | 35=A | 34=9 | 49=SENDER | 52=20121102-11:43:05.426 | 56=TARGET | 98=0 | 108=60 | 10=232 | 
20121102-11:43:05.438 : 8=FIX.4.4 | 9=114 | 35=5 | 34=72 | 49=TARGET | 52=20121102-11:43:05.427 | 56=SENDER | 58=MsgSeqNum too low, expecting 68 but received 9 | 10=246 | 
20121102-11:43:05.439 : 8=FIX.4.4 | 9=64 | 35=5 | 34=10 | 49=SENDER | 52=20121102-11:43:05.438 | 56=TARGET | 10=233 | 

**\* (manually reset sequence numbers to sender:68, target:72)

20121102-11:44:05.475 : 8=FIX.4.4 | 9=76 | 35=A | 34=68 | 49=SENDER | 52=20121102-11:44:05.475 | 56=TARGET | 98=0 | 108=60 | 10=035 | 
20121102-11:44:05.501 : 8=FIX.4.4 | 9=76 | 35=A | 34=73 | 49=TARGET | 52=20121102-11:44:05.482 | 56=SENDER | 98=0 | 108=60 | 10=029 | 
20121102-11:44:05.506 : 8=FIX.4.4 | 9=74 | 35=2 | 34=69 | 49=SENDER | 52=20121102-11:44:05.506 | 56=TARGET | 7=72 | 16=0 | 10=165 | 
20121102-11:44:05.518 : 8=FIX.4.4 | 9=107 | 35=4 | 34=72 | 43=Y | 49=TARGET | 52=20121102-11:44:05.511 | 56=SENDER | 122=20121102-11:44:05.511 | 36=74 | 123=Y | 10=069 | 
20121102-11:45:05.067 : 8=FIX.4.4 | 9=64 | 35=0 | 34=74 | 49=TARGET | 52=20121102-11:45:05.056 | 56=SENDER | 10=236 | 
20121102-11:45:06.070 : 8=FIX.4.4 | 9=64 | 35=0 | 34=70 | 49=SENDER | 52=20121102-11:45:06.070 | 56=TARGET | 10=229 | 

**\* (restarted the application here - sender MsgSeqNum incorrectly set back to 1)

20121102-11:45:17.538 : 8=FIX.4.4 | 9=75 | 35=A | 34=1 | 49=SENDER | 52=20121102-11:45:17.538 | 56=TARGET | 98=0 | 108=60 | 10=233 | 
20121102-11:45:17.550 : 8=FIX.4.4 | 9=114 | 35=5 | 34=75 | 49=TARGET | 52=20121102-11:45:17.539 | 56=SENDER | 58=MsgSeqNum too low, expecting 71 but received 1 | 10=244 | 
20121102-11:45:17.571 : 8=FIX.4.4 | 9=63 | 35=5 | 34=2 | 49=SENDER | 52=20121102-11:45:17.571 | 56=TARGET | 10=188 | 

**\* (manually reset sequence numbers to sender:71, target:76)

20121102-11:46:17.589 : 8=FIX.4.4 | 9=76 | 35=A | 34=71 | 49=SENDER | 52=20121102-11:46:17.589 | 56=TARGET | 98=0 | 108=60 | 10=040 | 
20121102-11:46:17.614 : 8=FIX.4.4 | 9=76 | 35=A | 34=76 | 49=TARGET | 52=20121102-11:46:17.597 | 56=SENDER | 98=0 | 108=60 | 10=044 | 
20121102-11:47:17.162 : 8=FIX.4.4 | 9=64 | 35=0 | 34=77 | 49=TARGET | 52=20121102-11:47:17.136 | 56=SENDER | 10=243 | 
20121102-11:47:18.164 : 8=FIX.4.4 | 9=64 | 35=0 | 34=72 | 49=SENDER | 52=20121102-11:47:18.164 | 56=TARGET | 10=240 | 
20121102-11:48:17.208 : 8=FIX.4.4 | 9=64 | 35=0 | 34=78 | 49=TARGET | 52=20121102-11:48:17.199 | 56=SENDER | 10=254 | 
20121102-11:48:18.208 : 8=FIX.4.4 | 9=64 | 35=0 | 34=73 | 49=SENDER | 52=20121102-11:48:18.208 | 56=TARGET | 10=241 | 
20121102-11:49:17.255 : 8=FIX.4.4 | 9=64 | 35=0 | 34=79 | 49=TARGET | 52=20121102-11:49:17.246 | 56=SENDER | 10=249 | 
20121102-11:49:18.255 : 8=FIX.4.4 | 9=64 | 35=0 | 34=74 | 49=SENDER | 52=20121102-11:49:18.255 | 56=TARGET | 10=245 | 
20121102-11:50:17.304 : 8=FIX.4.4 | 9=64 | 35=0 | 34=80 | 49=TARGET | 52=20121102-11:50:17.287 | 56=SENDER | 10=238 | 
20121102-11:50:18.305 : 8=FIX.4.4 | 9=64 | 35=0 | 34=75 | 49=SENDER | 52=20121102-11:50:18.305 | 56=TARGET | 10=234 | 

**\* (restarted the application here - sender MsgSeqNum incorrectly set back to 1)

20121102-11:50:25.406 : 8=FIX.4.4 | 9=75 | 35=A | 34=1 | 49=SENDER | 52=20121102-11:50:25.405 | 56=TARGET | 98=0 | 108=60 | 10=221 | 
20121102-11:50:25.433 : 8=FIX.4.4 | 9=114 | 35=5 | 34=81 | 49=TARGET | 52=20121102-11:50:25.406 | 56=SENDER | 58=MsgSeqNum too low, expecting 76 but received 1 | 10=234 | 
20121102-11:50:25.451 : 8=FIX.4.4 | 9=63 | 35=5 | 34=2 | 49=SENDER | 52=20121102-11:50:25.451 | 56=TARGET | 10=180 | 
20121102-11:51:25.461 : 8=FIX.4.4 | 9=75 | 35=A | 34=3 | 49=SENDER | 52=20121102-11:51:25.461 | 56=TARGET | 98=0 | 108=60 | 10=226 | 
20121102-11:51:25.470 : 8=FIX.4.4 | 9=114 | 35=5 | 34=82 | 49=TARGET | 52=20121102-11:51:25.461 | 56=SENDER | 58=MsgSeqNum too low, expecting 76 but received 3 | 10=239 | 
20121102-11:51:25.470 : 8=FIX.4.4 | 9=63 | 35=5 | 34=4 | 49=SENDER | 52=20121102-11:51:25.470 | 56=TARGET | 10=184 | 

My config is as follows:

[DEFAULT]
ConnectionType=initiator
ReconnectInterval=60
FileStorePath=c:\FIX\store
FileLogPath=c:\FIX\logs
HeartBtInt=60

[SESSION]
BeginString=FIX.4.4
SenderCompID=SENDER
TargetCompID=TARGET
SocketConnectHost=127.0.0.1
SocketConnectPort=10044
UseDataDictionary=Y
DataDictionary=C:\FIX\FIX44.xml
StartTime=06:00:00
EndTime=05:59:00

This is a critical problem as the service may be restarted several times during the trading day, and each time it came up the FIX connection would not be able to reconnect unless manually reset.  I am using v1.3.0.

Campbell

**Comment by ajitag09** [comment]
Hi
My quickfix sequence number is getting reset at sunday midnight. I stop my service on saturday night and started on monday morning, but sequence number was reset. I have sun-sun with start and end time as 00:00:00
