### ISSUE TITLE
SocketInitiator not using common interface

### ISSUE THREAD

**Issue by TomasVetrovsky** [connamara/quickfixn#177]
SocketInitiator has different interface than ThreadedSocketAcceptor (interface extended in the commit bellow). It does not allow to specify SessionFactory from
the outside. It also stores private variables that are newer used (deleted).

https://github.com/TomasVetrovsky/quickfixn/commit/63f2d5785307d49abaa8bddb2c7620a495a851be

**Comment by gbirchmeier** [comment]
Not sure when this changed, but neither SocketInitiator nor ThreadedSocketAcceptor take a SessionFactory parameter anymore.  I'm closing this.
