### ISSUE TITLE
Built in SSL

### ISSUE THREAD

**Issue by jcwild** [connamara/quickfixn#18]
Would it be possible to integrate SSL into QuickFIX/n?  We currently have to set up stunnel around the FIX connections so it would be fantastic to remove this requirement and allow it to be a configuration option.

**Comment by hadagali** [comment]
HI does QuickFIX/n support SSL with .pem certificates and what are the config parameters, pls point me to the doc if any.
http://quickfixn.org/tutorial/configuration.html#ssl this site does nor provide teh SSL settings

**Comment by chriskarpyszyn** [comment]
Look one post above yours.

>No, right now it only supports PKCS12.

>I think we really should support pem, but no one has written it.
