### ISSUE TITLE
Move to .NET 4.0??  Hey community, I need your input.

### ISSUE THREAD

**Issue by gbirchmeier** [connamara/quickfixn#188]
I've had multiple requests to move this thing to .NET 4.0.

The advantages of this seem clear.

But... are there any reasons to **not** do this?  Are any of you using 3.5 and will be hurt by such a move?  (Does anyone use 3.5 anymore?)

Please chime in.

**Comment by arkadiuszwojcik** [comment]
Is there any plan to create NuGet package for this project ?
