### ISSUE TITLE
Embedding the FIX<version>.xml as a resource into the QuickFix.dll

### ISSUE THREAD

**Issue by DHirani** [connamara/quickfixn#207]
If you can change the SessionFactory method createDataDictionary to be virtual then I can override it to use the stream which is already supported by the DataDictionary constructor but is never used.

Change
 protected DataDictionary.DataDictionary createDataDictionary(SessionID sessionID, QuickFix.Dictionary settings, string settingsKey, string beginString)

To
protected virtual DataDictionary.DataDictionary createDataDictionary(SessionID sessionID, QuickFix.Dictionary settings, string settingsKey, string beginString)

Or you could store the FIX<version>.xml as a resource that you load dynamically.

**Comment by gbirchmeier** [comment]
No follow up.
