### ISSUE TITLE
ReconnectInterval and user vs. spontaneous reconnects?

### ISSUE THREAD

**Issue by roji** [connamara/quickfixn#212]
Respecting ReconnectInterval (30 seconds by default) may be a bad idea for cases where the reconnect happens because certain events, e.g. a manual user-initiated reconnect.

It might even make sense to say that it should _only_ take effect because of "spontaneous" disconnect events, i.e. dropped connection etc.

If this seems like a good idea, we could set a flag on the session to indicate whether we just had a spontaneous disconnect. When reconnecting, we would only honor ReconnectInterval if this flag is set.

What do you think?

**Comment by gbirchmeier** [comment]
Closing this stale issue.

Reach out if you think this still has merit and want to pursue it.
