### ISSUE TITLE
Encoding mismatch causes faulty length and checksum

### ISSUE THREAD

**Issue by Meertman** [connamara/quickfixn#216]
Hi all,

When sending FIX messages using the QuickFixN library to a broker we have seen that sometimes an error gets thrown indicating that either the length or the checksum of the message is incorrect.

After analysing this further we have deduced that the broker is sending the message using the ISO-8859-1 encoding. This causes problems with at least the following character "£" in regards to length or checksum.

I have made the necessary changes localy to make the encoding configurable and use UTF-8 as default encoding if no encoding is configured. 

Kind regards,
Rob

**Comment by amichair** [comment]
Just to make sure - the suggested fix was rejected? If so, that's unfortunate, seeing that this is how FIX is being used 'in the wild'. QuickFix/J had the same issues reported by various users and opted for the same fix. Some QuickFixN users are experiencing the same thing. Rejecting this fix simply means that QuickFixN can't play along with anyone else that uses non-ASCII data this way. The current behaviour of using UTF-8 only is neither here nor there.

It would be wonderful if everyone properly supported the Encoded fields, but this is not (yet?) the case, so you might as well have a working workaround for now...

**Comment by Meertman** [comment]
@amichair, that is correct. The suggested fix was rejected. However, we have been using the fix in our own version of QuickFixN. However, while the fix is not that difficult, this introduces additional work every time we want to use a newer version of QuickFixN.

**Comment by amibar** [comment]
@amichair @gbirchmeier @Meertman 
I created a PR to fix this.
See https://github.com/connamara/quickfixn/pull/431

**Comment by Meertman** [comment]
@amibar, I had also suggested a PR for this, but it was rejected. See #217

**Comment by amichair** [comment]
So, this issue has been open for over 4 years. Multiple related issues were reported, users waste time on this every time they re-discover it, all seem to agree the solution is reasonable, two PRs implement it, as do other FIX projects, it is backwards-compatible yet provides flexibility to those who need it, and from the issues/comments you can see the need is real.

Is there a compelling reason why this isn't been merged?

**Comment by david-gibbs-ig** [comment]
There are 103 users watching this issue, presumably to find out when they can stop needing to maintaining a private branch to work around it.  Inter-operability is the purpose of a FIX engine and in the spirit of international co-operation I think that this issue does need to be addressed. The community has submitted some patches.  If these are unsuitable, why so ?

**Comment by gbirchmeier** [comment]
Resolved in #531.

Apologies to all for not correctly recognizing this problem when it originally arose, and the long time span that it took to resolve it properly. The latest commit is fixed and fully compatible with QF/j implementations. QF/n and QF/j now both use iso-8859-1 (aka latin1) as default encoding, which will allow many standard european characters that UTF-8 was messing up.

**Comment by david-gibbs-ig** [comment]
Thank you Grant, that's really great news.
