### ISSUE TITLE
Resend causes invalid body length

### ISSUE THREAD

**Issue by yapfoofy** [connamara/quickfixn#223]
When the library resend Execution Report with parties group it doesn't generate the message string correctly (missing party tags) and causes invalid body length.

The problem is in "protected void NextResendRequest(Message resendReq)" .

original code:
Message msg = new Message(msgStr);

my solution:
Message msg = new Message();
msg.FromString(
                            msgStr,
                            this.ValidateLengthAndChecksum,
                            this.SessionDataDictionary,
                            this.ApplicationDataDictionary,
                            this.msgFactory_);

**Comment by gbirchmeier** [comment]
Stale.  Haven't seen other reports in recent years.  Either it got fixed somehow or it's a really special case.
