### ISSUE TITLE
Unhandled RejectLogon error

### ISSUE THREAD

**Issue by v-vayer** [connamara/quickfixn#227]
I'm trying to authenticate a connection in the FromAdmin handler. In case of wrong username/password combination, I throw the RejectLogon exception. I'd expect the exception to bubble up, log the error and silently disconnect the connection. Instead it throws an unhandled error message. This obviously kills the worker thread and disconnects the users, but in a very ungraceful manner.
Bellow is the code:

public void FromAdmin(Message msg, SessionID sessionID) {
     switch (msg.Header.GetString(Tags.MsgType))
     {
          case MsgType.LOGON:
               throw new RejectLogon("Wrong username/password combination");
               break;
     }
}

**Comment by gbirchmeier** [comment]
I tried to reproduce this just now, but everything seemed to be working correctly.  My acceptor app threw it, and the engine caught it, then sent a Logout with my exception message back to the initiator.  Everything looked correct in the logs on either side of the connection.

**Comment by v-vayer** [comment]
Obviously irrelevant more than 10 years later!

**Comment by gbirchmeier** [comment]
Not totally obvious; I'd feel like a real clown if I closed it and it was still actually happening.

As for the 10+ years: Yeah, I know 😞.  I'm trying to clear the backlog as much as I can and stay better on top of things going forward.
