### ISSUE TITLE
setfield functionality is randomly extra slow

### ISSUE THREAD

**Issue by bahr52** [connamara/quickfixn#228]
In running a stopwatch to see where slowness comes from, i discovered that the .setField or .set methods from time to time slow to a halt. 

FixOrdCxlRequest.set(New Side(Side.SELL_SHORT))
or 
FixMessage.getHeader.setField(QuickFix.TargetSubID.FIELD, "ARCA")

Most of the time, zooms past this code way under millisecond. However, sometimes the same code takes 163 milliseconds. 

Any ideas how to improve this?

**Comment by gbirchmeier** [comment]
Probably not an issue.
