### ISSUE TITLE
Deeper level groups not handled by the generated MessageFactory.

### ISSUE THREAD

**Issue by jpetterl** [connamara/quickfixn#229]
Hi,

I had some problems with the generator when my data dictionary had more than one level of group messages for a particular message type. e.g.
&lt;message name="QuoteRequest" msgtype="R" msgcat="app"&gt;
        &lt;field name="QuoteID" required="Y" /&gt;
        &lt;group name="NoStructures" required="Y"&gt;
                &lt;field name="StructureNumber" required="Y" /&gt;
                &lt;field name="StructureName" required="Y" /&gt;
                &lt;group name="NoLegs" required="Y" &gt;
                        &lt;field name="LegRefID" required="Y" /&gt;
                &lt;/group&gt;
        &lt;/group&gt;
&lt;/message&gt;

When a message of this type was received and deserialized through the message factory the NoStructures group correctly hydrated to the right NoStructuresGroup instance. However, the NoLegs part ended up being a generic Group instance.

It appears as though the MessageFactory's Create() method needs to include:
        case QuickFix.Fields.Tags.NoStructures: return new QuickFix.FIX44FxAll.QuoteRequest.NoStructuresGroup();
        case QuickFix.Fields.Tags.NoLegs: return new QuickFix.FIX44FxAll.QuoteRequest.NoStructuresGroup.NoLegsGroup();
where the generated code was missing the second part.

To this end I modified the generate script (message_factory_gen.rb) to loop recursively and therefore also include child groups (see new code below. Please be gentle, my first and only ruby code).

Is there anyone out there who has had the same problem? If so, can you please advise if this is a bug in the generate script or if there is simply something I'm not understanding?

Thanks,
Petter

```
def self.gen_method_group_ifs(messages,fixver)
    indent = " "*4*4
    lines = Array.new
    messages.each {|m|
        if(m[:groups].length > 0)
            lines << indent + "if (QuickFix.#{fixver}.#{m[:name]}.MsgType.Equals(msgType))"
            lines << indent + "{"
            lines << indent + "    switch (correspondingFieldID)"
            lines << indent + "    {"

            lines << gen_method_group_case(m,"",fixver)

            lines << indent + "    }"
            lines << indent + "}"
            lines << ""
        end
        }
    lines.join("\n")
end
def self.gen_method_group_case(gs,parentStr,fixver)
    indent = " "*4*4
    lines = Array.new
    gs[:groups].each {|g|
        if(parentStr=="")
            lines << indent + "        case QuickFix.Fields.Tags.#{g[:name]}: return new QuickFix.#{fixver}.#{gs[:name]}.#{g[:name]}Group();"
            lines << gen_method_group_case(g, gs[:name],fixver)
        else
            lines << indent + "        case QuickFix.Fields.Tags.#{g[:name]}: return new QuickFix.#{fixver}.#{parentStr}.#{gs[:name]}Group.#{g[:name]}Group();"
            lines << gen_method_group_case(g, parentStr + "." + gs[:name] + "Group",fixver)
        end
        }
    lines.join("\n")
end
```

**Comment by gbirchmeier** [comment]
Stale.  Strongly suspect this got fixed at some point.
