### ISSUE TITLE
Not receiving logout message after enabling FIX5.0 SP1

### ISSUE THREAD

**Issue by Devoji** [connamara/quickfixn#243]
I use QuickFIX/n for my OMS.

I developed my OMS with my QuickFIX/n Engine enabled for FIX5.0. Later I needed to upgrade it to FIX5.0SP1 which I did by moving the neccessary files into the application.

After doing this I discovered that Execution Reports (after properly arranging my data dictionary) could not be received because of a mismatch in the type of message coming in. Execution Report coming was of type FIX5.0 but application was expecting FIX5.0SP1.

To fully enable FIX5.0SP1, I adjusted the file DefaultMessageFactory.cs

public DefaultMessageFactory()
{
  _factories[FixValues.BeginString.FIX40] = new QuickFix.FIX40.MessageFactory();
  _factories[FixValues.BeginString.FIX41] = new QuickFix.FIX41.MessageFactory();
  _factories[FixValues.BeginString.FIX42] = new QuickFix.FIX42.MessageFactory();
  _factories[FixValues.BeginString.FIX43] = new QuickFix.FIX43.MessageFactory();
  _factories[FixValues.BeginString.FIX44] = new QuickFix.FIX44.MessageFactory();
  _factories[FixValues.BeginString.FIX50] = new QuickFix.FIX50SP1.MessageFactory();
}

FIX50SP1 above used to be FIX50. With this, I can receive my execution reports.

After this, when I initiate LOGOUT, my application sends the logout message, but the logout message from the acceptor is never received. Application then waits and logs out because it times out (LogoutTimeout=5).

When I reverse the FIX50SP1 in the DefaultMessageFactory.cs file, logout functions normally but I will not get my execution reports.

What is the recommended way to enable FIX50SP1 without having issues.

**Comment by gbirchmeier** [comment]
Stale.  Probably fixed.
