### ISSUE TITLE
Sequence number being reset although not a new session

### ISSUE THREAD

**Issue by adutois** [connamara/quickfixn#254]
Hi,
I came up with a behavior which I think is an issue. It's highly related to issues #22, #139 and #151. It seems there is still one case where reset doesn't work as expected (I'm using version 1.5.0.0).

Let's have an initiator's config set on daily sessions (from 7h to 22h). The case is the following:
Step 1: Service is launched on middle of day 1
Step 2 : Session ends on day 1 at 22h
Step 3: Session starts on day 2 at 7h
Step 4 : Service is stopped and restarted on middle of day 2
-> expected: resume sequence numbers from session started at 7h
-> issue: reset is done

Note that after first stop/restart, each time a stop/restart is done (on day 2), it will work as expected (sequence numbers will be resumed).

It's because the IsNewSession method performs a check against the store's creation time (and following end time). 
For described case, that tmeans: creation time < next end time < now. So it thinks it's a new session and reset is done although between last end time and now, there was a session start.

Where I get confused is 
1. where does the creation time come from?
2. what is the time stored in .session file?
When I look at my file history (.session) I see it stores a time which is a few seconds later than end time (e.g. 22:00:10). If it was this time which was tested instead of "creation time", the problem won't appear.
Indeed, we would have: 
tested time (D1-22:00:10) < now < next end time (D2-22:00:00)

Thanks a lot for your feedback.

**Comment by gbirchmeier** [comment]
super stale.  Probably not an issue.
