### ISSUE TITLE
ClientHandlerThread not disposing FileLog

### ISSUE THREAD

**Issue by joseph-orbis** [connamara/quickfixn#255]
We have tests that create an in-memory acceptor per test and occasionally some tests would fail with this error:
Error accepting connection: The process cannot access the file 'C:\xxxx\bin\Debug\ClientHandlerThread-0-Debug.messages.current.log' because it is being used by another process.

It seems to be caused by the ClientHandlerThread in previous test not releasing the lock on the file when the acceptor was stopped, and therefore the file lock wasn't explicitly released. Since it's ClientHandlerThread who created the FileLog instance in the first place it should be responsible for disposing it when it quits.

**Comment by mgatny** [comment]
Closed by PR #335
