### ISSUE TITLE
Overzealous SSL Certificate Validation

### ISSUE THREAD

**Issue by neilejgreen** [connamara/quickfixn#264]
The validation of SSL certificates in StreamFactory.cs seems to be a bit overzealous.  

ContainsEnhancedKeyUsage checks to see if there is an appropriate Enhanced Key Usage (client or server) in the certificate.  However, as I understand it, the certificate is only invalid if the usage is missing _and_ other usages are defined.  If the certificate does not contain Enhanced Key Usages then the certificate should still be valid.   

http://security.stackexchange.com/a/38484/46617
http://tools.ietf.org/html/rfc5280#section-4.2.1.12

**Comment by brobits** [comment]
Your understanding of X.509 certificates with respect to TLS is correct if and only if (1) the certificate issuer does not deem the Extended Key Usage extension critical (omits the extension), and (2) the certificate using application does not require EKU:

> Certificate using applications MAY require that the extended key usage extension be present and that a particular purpose be indicated in order for the certificate to be acceptable to that application.

QF/n is compliant as-is, but I can see the benefit of accepting X.509 certificates with an omitted EKU.  If QF/n's stringent TLS EKU requirements are affecting your organization, feel free to make the change on a fork and submit a PR following our [contributor guidelines](../blob/master/CONTRIBUTING.md).  If you do, please re-open and tag this issue on your PR (include "#264" somewhere in your pull request) so we can properly follow this issue.

Thanks for helping support QF/n.
