### ISSUE TITLE
SocketInitiator.Dispose object disposed exception

### ISSUE THREAD

**Issue by frostius** [connamara/quickfixn#272]
v1.5.0
Calling SocketInitiator.Dispose() or Stop() results in an object disposed exception.
I have fixed this (in my local version) by adding a check for disposed in the AbstractInitiator.Dispose() method.  It looks like dispose handling could use some attention across the board.

Revised method:
        protected virtual void Dispose(bool disposing)
        {
            if( _disposed ) return;
            this.Stop();
            _disposed = true;
        }

**Comment by gbirchmeier** [comment]
addressed by #505
