### ISSUE TITLE
DateTimeConverter.Convert issue

### ISSUE THREAD

**Issue by arcoba** [connamara/quickfixn#279]
Hi,
using quickfixn on a computer with "." as time separator, the method 
public static string DateTimeConverter.Convert(System.DateTime dt, bool includeMilliseconds)
return a incorrect string (time contains "." instead of ":" as time separator because .net use local globalization settings) .

This happens even if the formatting parameter ("{0:yyyyMMdd-HH:mm:ss.fff}") is passed to the string.Format function.

Fix protocol specify that the time separator must be ":", so how can I resolve this issue..?

Code:
public static string Convert(System.DateTime dt, bool includeMilliseconds)
{
   if(includeMilliseconds)
      return string.Format(DATE_TIME_FORMAT_WITH_MILLISECONDS, dt);  
   return string.Format(DATE_TIME_FORMAT_WITHOUT_MILLISECONDS, dt);
}

Best regards,
Arcoba.

**Comment by brobits** [comment]
The DateTime you pass to the `DateTimeConverter` should use a FIX-compliant DateTime culture.  See: https://msdn.microsoft.com/en-us/library/5hh873ya(v=vs.90).aspx

**Comment by AThomsen** [comment]
Unit tests (CanConvertFromDateTimeWithMicrosecondsToValidStringWithMilliSecondPrecision and others) ) currently fails when running on a computer with '.' as time separator!
