### ISSUE TITLE
SessionFactory

### ISSUE THREAD

**Issue by minskowl** [connamara/quickfixn#284]
Possible add some session factory for add\remove sessions without restart server?

**Comment by chizz5056** [comment]
This functionality is now available in the following branch: 
https://github.com/martinadams/quickfixn/tree/dynamic_sessions

There's no unit tests as yet, but sessions can be added or removed (or a combination of both to 'update' a session) via the AddSession() and RemoveSession() methods.

**Comment by gbirchmeier** [comment]
A PR has since added this.
