### ISSUE TITLE
Log-file access error while accepting connection

### ISSUE THREAD

**Issue by yahorby** [connamara/quickfixn#300]
I've created a small sample project that demonstrates an unexpected log-file access error occurred when server trying to accept connection.

Steps to reproduce:
1. Build **FixIOLogException** sample project.
2. Run **FIXServer** app. 
3. Run **FIXClient** app.
4. An unexpected error occurred while trying to establish a connection:

```
Starting server ...

Press Enter to stop
Error accepting connection: The process cannot access the file 
'C:\FixIOLogException\FIXServer\bin\Debug\fixlog\ClientHandlerThread-0-Debug.messages.current.log'
 because it is being used by another process.
```

Is there a way to fix this issue?

Attached sample project: https://drive.google.com/uc?id=0B-LkSR9nTvvLRmNGeDB5Vl9XckE&export=download

**Comment by yahorby** [comment]
The following changes in the Quickfix\n source code can get rid of this exception:
>**ThreadedSocketReactor.cs**
>
>
>**–**     private long nextClientId_ = 0;
>**+**     private __static__ long nextClientId_ = 0;
>
>
>
>**–**     ClientHandlerThread t = new ClientHandlerThread(client, nextClientId_++, sessionDict_, socketSettings_);
>**+**     **Interlocked.Add(ref nextClientId_, 1);**
>**+**     ClientHandlerThread t = new ClientHandlerThread(client, **nextClientId_**, sessionDict_, socketSettings_);


Attached ***ThreadedSocketReactor.cs.patch*** file: https://docs.google.com/uc?authuser=0&id=0B-LkSR9nTvvLNFBvVVYxdmVLbXM&export=download


Is this a correct fix for the issue?

**Comment by requiem202** [comment]
I came across this issue today.
My cause is using multiple acceptor sessions, each has its own ClientHandlerThread, led to the same file name across all threads.

Changed nextClientId_ to static with synchronized access as @yahorby patch helped.

**Comment by requiem202** [comment]
I came across this issue today.
My cause is using multiple acceptor sessions, each has its own ClientHandlerThread, led to the same file name across all threads.

Changed nextClientId_ to static with synchronized access as @yahorby patch helped.

**Comment by pavka1799** [comment]
There is a workaround to avoid the issue without changing source code of the library: specify different "DebugFileLogPath" in each "[SESSION]" section, so file with the same name will be placed in different directories.

**Comment by gbirchmeier** [comment]
The Debug log has been removed and replaced with a better "NonSessionLog" implementation.  This issue is no longer relevant.
