### ISSUE TITLE
QuickFIX Invalid message: Expected BodyLength=454, Recieved BodyLength=469

### ISSUE THREAD

**Issue by kmdshuaib** [connamara/quickfixn#304]
When receiving a ExecutionReport (35=n) i receive the below error

QuickMessage: Invalid message: Expected BodyLength=454, Recieved BodyLength=469

Sample Vendor Message

8=FIX.4.29=46935=n34=13208369=1952=20150324-08:07:58.91943=Y49=CME50=7056=UAT12357=P122=20150324-07:57:04.201212=350213=8=FIX.4.29=31435=834=15294369=775852=20150324-07:57:04.19949=CME50=7056=AZT000N57=DUMMY143=US,IL1=003316=011=ACP142718382415514=017=70477:206612220=037=7029490619138=1039=040=241=044=50448=806054=155=HW59=060=20150324-07:57:04.198107=HWJ5150=0151=10167=FUT432=201503241028=Y9717=ACP142718382415510=03910=097

Please help to resolve this 

Thanks in Advance

**Comment by brobits** [comment]
Could you please re-submit this issue with the FIX log showing the vendor's outbound message causing the body length error, and your reject reply?  Thanks.
