### ISSUE TITLE
Message.fromString loses Tag order.

### ISSUE THREAD

**Issue by AtanuSinha** [connamara/quickfixn#307]
Hi, 

I am trying to create a message from a string, but it looses its Tag order for a specific repeating group. Here's the workflow:

1. Create a AllocationInstruction message
2. Save the message as string in DB.
3. Take the message string from DB and recreate it using Message.frsomString
4. A particular Tag order changes.

What I have done so far:

- Verified I use the same  DataDictionary while creating the message and later recreating it from the string equivalent. 
- Tried creating the AllocationInstruction message fromString, but same result. 

I am guessing, it has to do with the DataDictionary. How can ensure I am using the right one?
I will add my code and result to this thread shortly..

**Comment by AtanuSinha** [comment]
string strDictPath = System.Configuration.ConfigurationManager.AppSettings["FIXDictionary"];
 QuickFix.DataDictionary.DataDictionary dict = new uickFix.DataDictionary.DataDictionary(strDictPath); 
...
...
Message msg = new Message(xMess.FIXMessage, dict, false);  // This is where the Tag Order changes 

I also tried:

QuickFix.FIX44.AllocationInstruction oAlloc = new QuickFix.FIX44.AllocationInstruction();
 oAlloc.FromString(xMess.FIXMessage, false, dict, dict);    //This is where the Tag Order changes


So, in the msg string I have, 78,79,80,12,13 But what I get back is 78,79,12,13,80.

Any suggestion??

**Comment by chriskarpyszyn** [comment]
What was the solution?
