### ISSUE TITLE
Non-US timezones creating gaps in the charts

### ISSUE THREAD

**Issue by connamara-zendesk** [connamara/quickfixn#308]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [84](https://connamara.zendesk.com/agent/#/tickets/84)
**Priority:** normal
**Zendesk assignee:** Futures Institute L3/A

**Original ticket content:**

While Jim was in Amsterdam he notice gaps in the charts.  We weren't seeing the gaps here in Chicago, but when we switched the computer times to Non-US timezones we saw the gaps.

**Comment by connamara-zendesk** [comment]
*Comment from Zendesk by koconnell@connamara.com at 2015-04-21 13:45:44 UTC:*

<p>While Jim was in Amsterdam he notice gaps in the charts.  We weren&#39;t seeing the gaps here in Chicago, but when we switched the computer times to Non-US timezones we saw the gaps.</p>

**Comment by koconnell** [comment]
Sorry.  Wrong project.
