### ISSUE TITLE
make "[SESSION]" in config file case-insensitive (to be like QF/j)

### ISSUE THREAD

**Issue by creyes52** [connamara/quickfixn#315]
I had a previous settings file like this:
[session]
BeginString=FIX.4.4
FileStorePath=store
FileLogPath=log

But it turns out that I had to change to upper case in order to get it working, or it simply doesn't read the session and never tries to connect.
[SESSION]
BeginString=FIX.4.4
FileStorePath=store
FileLogPath=log

**Comment by gbirchmeier** [comment]
Good catch.  I changed the title to better summarize this issue.

**Comment by gbirchmeier** [comment]
This was an easy one, so I just knocked it out.
