### ISSUE TITLE
Bug: Tag 269 appears more than once with trying to parse MarketDataSnapshotFullRefresh

### ISSUE THREAD

**Issue by Lambda211** [connamara/quickfixn#330]
Hi,
I have been intercepting a very disturbing bug today when trying to establish a new connection with LMAX. Please note this is not my first connection with quickFix (already connected to 7 brokers successfully). When QuickFix tries to parse an MarketDataSnapshotFullRefresh (35=W) message, it generates a reject message telling me that tag 269 appears more than once:

20150710-17:04:07.406 : 8=FIX.4.4 9=167 35=W 49=LMXBDM 56=****** 34=2 52=20150710-17:04:10.860 262=0 48=100667 22=8 268=2 269=0 270=0.94378 271=50 272=20150710 273=17:04:09.645 269=1 270=0.94396 271=50 10=227
20150710-17:04:07.459 : 8=FIX.4.4 9=117 35=3 34=77 49=***** 52=20150710-17:04:07.417 56=LMXBDM 45=2 58=Tag appears more than once 371=269 372=W 373=13 10=073

Please note that the only element that might not be FIX 4.4 compliant is that the message do not reference the symbol but a securityID, proper to LMAX. However this does not explain why the message parsing seems to get stuck when parsing group NoMDEntries.

Please find below  a simplified version of message W I use within my dictionary for LMAX. 

    <message name="MarketDataSnapshotFullRefresh" msgtype="W" msgcat="app">
      <field name="MDReqID" required="Y" />
      <field name="SecurityID" required="Y" />
      <field name="SecurityIDSource" required="Y" />
      <group name="NoMDEntries" required="Y">
        <field name="MDEntryType" required="Y" />
        <field name="MDEntryPx" required="N" />
        <field name="MDEntrySize" required="N" />
        <field name="MDEntryDate" required="N" />
        <field name="MDEntryTime" required="N" />
      </group>
      <field name="ApplQueueDepth" required="N" />
      <field name="ApplQueueResolution" required="N" />
    </message>

**Comment by gbirchmeier** [comment]
Hm.  That's weird.  Your message looks ok by your DD.

Did you remember to put `UseDataDictionary=Y` in your config?  Are you sure that `DataDictionary=` is going to the right DD xml file?  (I know, these would be rookie mistakes, but still have to check them)

Message breakdown, for the record:

```
8=FIX.4.4
9=167
35=W
49=LMXBDM
56=******
34=2
52=20150710-17:04:10.860

^^^end of header

262=0 MDReqID
48=100667 security id
22=8 security id source

268=2 NoMDEntries
- 269=0 MDEntryType
  270=0.94378 MDEntryPx
  271=50 MDEntrySize
  272=20150710 MDEntryDate
  273=17:04:09.645 MDEntryTime

- 269=1 MDEntryType
  270=0.94396 MDEntryPx
  271=50 MDEntrySize

10=227
```

**Comment by Lambda211** [comment]
Oh hell please kill me. I m sorry for disturbance.

**Comment by gbirchmeier** [comment]
Hahahahaha!  No problem  :)
