### ISSUE TITLE
Creating a group such as no partyid causes empty group to be created and throws checksum off by 1

### ISSUE THREAD

**Issue by aram83** [connamara/quickfixn#332]
Creating a group such as no partyid causes empty group to be created and throws checksum off by 1

**Comment by gbirchmeier** [comment]
This is a terrible issue report.  Where is your demonstration code?  Example input/outputs?

Anyway, this is a highly visible feature with many tests that use it, so I'm positive that it is not broken.  You have made some kind of mistake in your code, but I can't tell you what that might be based on such an insubstantial issue description.

Please see [this page](http://quickfixn.org/help) to find out the various methods for requesting help.  I recommend the mailing list, but StackOverflow is also nice.

**Comment by aram83** [comment]
I found this issue which is exactly what I see as well.

http://www.quickfixj.org/jira/browse/QFJ-765

How can I fix this scenario?

**Comment by gbirchmeier** [comment]
That's a Quickfix/J bug - the java port of QuickFIX.

I'm not going to help you on Github.  Please get help via one of the options here:
http://quickfixn.org/help

Or... if you're using QF/j (Java), visit quickfixj.org and explore their help options.
