### ISSUE TITLE
Was this issue resolved? http://www.quickfixj.org/jira/browse/QFJ-765

### ISSUE THREAD

**Issue by aram83** [connamara/quickfixn#333]
I have this same scenario.  How can I resolve this?

http://www.quickfixj.org/jira/browse/QFJ-765

**Comment by gbirchmeier** [comment]
Please stop submitting issues unless you think you've found a real bug.

The proper place to ask questions is on the mailing list or on StackOverflow.
See here: http://quickfixn.org/help

Furthermore, that's a bug for Quickfix/J, the Java port of Quickfix.  This GitHub repo is for Quickfix/n, the C# port.  Please figure out which one you using.

**Comment by aram83** [comment]
I actually have this exact same issue on the .NET version which I'm using.  There is no associated .net issue like this?

**Comment by gbirchmeier** [comment]
I am not aware of any.

Please show me your FIX message that is triggering this bug.

Also, who is sending you this FIX message?  This would be an obscure bug because it is caused by the sender sending an invalid message.

**Comment by aram83** [comment]
I will get this shortly for you. thx for patience.

**Comment by gbirchmeier** [comment]
closed for lack of response
