### ISSUE TITLE
Quickfixn database implementation

### ISSUE THREAD

**Issue by mabochster** [connamara/quickfixn#339]
I have created session, message, messagelog, messagelog backup, eventlog, eventlog backup ,messages tables to try to migrate the logins to the DB instead, 

My problem is that the code has started to behave in a way that makes it impossible to continue normal  session.
The client for instance sends multiple logon request that never requests, and messes up the message count , so there is always a message reset happening, when I send an. for e.g advertisement message, I get a heartbeat as the the response.

I did not move entirely to a DB only solution and still rely on the MemoryStore for SeqNum and creation time, but I log all events when the sequence is updated.

The message Log
![image](https://cloud.githubusercontent.com/assets/12877655/9524810/3277b798-4ce1-11e5-8b5b-dfc635a69051.png)
The Event Log

![image](https://cloud.githubusercontent.com/assets/12877655/9525379/2dd9568a-4ce4-11e5-8fce-40827476885b.png)

So my code 
![image](https://cloud.githubusercontent.com/assets/12877655/9525537/e30699b4-4ce4-11e5-8b12-4935a15a7cd9.png)

Please not that the Acceptor and initiator are running on the same machine.

**Comment by mabochster** [comment]
My code Looks like this 
![image](https://cloud.githubusercontent.com/assets/12877655/9525480/90e9dea2-4ce4-11e5-9ea5-225aa729e37e.png)

If more info is required I am willing to provide.

**Comment by brobits** [comment]
This sounds like you have a threading issue in your implementation of a database store?  QuickFIX/n does not officially support a database implementation of the `IMessageStore` interface; only the `FileStore` and `MemoryStore` implementations are supported.

If you'd like some help on debugging your database storage threading model, you can head to the [QuickFIX/n mailing list](http://lists.quickfixn.com/listinfo.cgi/quickfixn-quickfixn.com) or [seek commercial support](https://www.connamara.com/quickfix/).
