### ISSUE TITLE
Only UTC time is supported

### ISSUE THREAD

**Issue by happiness123** [connamara/quickfixn#345]
I get this ‘Only UTC time is supported’ in 1.5.0 version what should I do?

**Comment by jcwild** [comment]
Are you upgrading from a different version of QuickFIX?  We get this when upgrading from QuickFIX to QuickFIX/n, and the solution there is to delete the contents of your “store” folder.  There’s some incompatibility between the formatting of the dates I think.

**Comment by happiness123** [comment]
Thanks

**Comment by gbirchmeier** [comment]
not a bug

**Comment by valdekjr** [comment]
Thanks. I was replacing the old quickfixengine (c++) to the new quickfixn and removing the old store folder solved the issue.
