### ISSUE TITLE
Logon issue

### ISSUE THREAD

**Issue by happiness123** [connamara/quickfixn#346]
FIX.4.4:202dc455-1bf9-4320-8212-d466b3355233->OKSERVERs------client onCreate 创
建Session-------FIX.4.4:202dc455-1bf9-4320-8212-d466b3355233->OKSERVERs
<event> Created session
<event> Connecting to 120.55.144.54 on port 9880
<event> Connection succeeded
<event> Session reset: ResetOnLogon
<event> Session reset: ResetSeqNumFlag
<outgoing> 8=FIX.4.49=18435=A34=149=202dc455-1bf9-4320-8212-d466b335523352=
20150907-13:02:54.80756=OKSERVERs98=0108=30141=Y553=username554=password=005
<event> Initiated logon request
<event> Session FIX.4.4:202dc455-1bf9-4320-8212-d466b3355233->OKSERVERs disconne
cting: System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现
有的连接。
   在 QuickFix.SocketInitiatorThread.ReadSome(Byte[] buffer, Int32 timeoutMillis
econds)
   在 QuickFix.SocketInitiatorThread.Read()
FIX.4.4:202dc455-1bf9-4320-8212-d466b3355233->OKSERVERs------client onLogout 退
出-------FIX.4.4:202dc455-1bf9-4320-8212-d466b3355233->OKSERVERs
<event> Session reset: ResetOnDisconnect

when I connect FIX/J  server, get this  what's wrong with my client,Can anybody help me？
Thanks

**Comment by gbirchmeier** [comment]
Do not use GitHub for help requests.  See http://quickfixn.org/help.html
