### ISSUE TITLE
SocketConnectHost

### ISSUE THREAD

**Issue by pearljam100** [connamara/quickfixn#347]
hi, if anyone can help or explain a bit more please. I have acceptor and initiator working via SocketConnectHost=127.0.0.1 but when I chnage my initiator.cfg and use some demo with different socket ip addresses I can not get initiator to work. Is it a firewall issue? How can I make use of Sample Initiator Settings File from http://quickfixn.org/tutorial/configuration.html#initiator? Many thanks

**Comment by chriskarpyszyn** [comment]
Please do not use Github to ask questions. Please use one of the following options listed at http://quickfixn.org/help.html.

**Comment by gbirchmeier** [comment]
not a bug
