### ISSUE TITLE
ssl documentation

### ISSUE THREAD

**Issue by gbirchmeier** [connamara/quickfixn#348]
We really need some better docs around the ssl feature.

This is a bit from Ian Clements on the mailing list (Sept 14, '15).  It could be a start:

```
I needed to use OpenSSL to turn my two pem files (Cert & key) into a pfx file with the following command –

OpenSSL pkcs12 –inkey c:\keys\key.pem –in c:\keys\cert.pem –export –out c:\keys\NewCert.pfx

Then with the following config everything connected great.

SSLEnable=Y
SSLValidateCertificates=N
SSLCheckCertificateRevocation=N
SSLCertificate=c:\Keys\NewCert.pfx
SSLCertificatePassword=xxxxxxx

Hope this helps others.  Would be good to include it in the SSL documentation to help others trying to migrate from stunnel with key and cert files.
```

**Comment by sachinp84** [comment]
@gbirchmeier ,

I tried to do the configuration as you mentioned, but it give me following error :

`Connection failed: Authentication failed because the remote party has closed the transport stream.`

Kindly advice on the same.

**Comment by gbirchmeier** [comment]
Unfortunately, I have little experience with this feature.  I didn't code it, and I haven't used it.

**Comment by jonfreedman** [comment]
I think the main issue with the SSL documentation is that it is not very clear which options are relevant for an acceptor, for an initiator or for both.

**Comment by oceanindian1987** [comment]
@gbirchmeier  - were you establishing as Initiator or Acceptor. Is there any plan provide proper documentation ?

**Comment by gbirchmeier** [comment]
@oceanindian1987 - see my Feb 24 comment

**Comment by gbirchmeier** [comment]
Closing due to staleness
