### ISSUE TITLE
extend timestamps to allow for nanoseconds?

### ISSUE THREAD

**Issue by gbirchmeier** [connamara/quickfixn#352]
Prompted by this question:

http://stackoverflow.com/questions/32778412/inet-nordic-fix-protocols-extending-to-nanosecond-granularity-timestamps

Some counterparties are making changes to include nano-seconds in timestamps.  Will this break existing apps?  Will QF/n truncate those zeros when parsing the times?  Can we extend it to retain the zeros in the created DateTime objects?

**Comment by gbirchmeier** [comment]
Relevant:  
http://www.fixtradingcommunity.org/pg/discussions/topicpost/2893609/

**Comment by jcwild** [comment]
This may need to be escalated.  Connections are going to start breaking as parties start sending microsecond/nanosecond timestamps.

E.g. 
`< 8=FIX.4.4|9=175|35=8|49=TB44|56=TF44|34=3|52=20170202-10:28:29|6=0|11=1835901|14=0|17=1877869114|22=8|37=1877869115|38=5000|39=0|48=ABT|54=2|55=ABT|60=20170202-10:24:58.123456|150=0|151=5000|10=069|`

Results in a Session level reject
`> 8=FIX.4.4|9=110|35=3|34=3|49=TF44|52=20170202-10:28:32.279|56=TB44|45=3|58=Incorrect data format for value|371=60|372=8|373=6|10=154|`

**Comment by cbusbey** [comment]
An update to this issue, we have a merged a contribution that covers microsecond precision, but nanosecond precision is still a feature we would like to get implemented.

**Comment by huwilly** [comment]
Hello,

First of all, thank you for your great work.
It looks like #459 adds this feature. So will there be a new release in the coming weeks ?
If so, it will be very helpful for everyone intending to comply with MiFID II.

Thank you.
Willy

**Comment by cbusbey** [comment]
Hi Willy,

459 should satisfy most MiFID II requirements, but bear in mind the caveat pointed out in that pr regarding limited nanosecond support.

We hope to make an official release in the near future, but in the meantime, feel free to grab the source from master and the library with this support today.

**Comment by huwilly** [comment]
Hi @cbusbey ,

It is noticed and the current nanosecond support is OK for me.
I will build the source if necessary. But for the moment, I can wait a few more weeks.
Thank you.

**Comment by dckorben** [comment]
The functionality is working but there isn't actually a mechanism to distribute the setting globally, case in point: ConvertToDateTime(string str) is statically set to TimeStampPrecision.Millisecond. This seems like a design problem with DateTimeConverter which should be an instance created by a session and not a static class.

**Comment by gbirchmeier** [comment]
I think this is is all sorted now.  If it's not, someone should open a new issue.
