### ISSUE TITLE
delete file + openfile

### ISSUE THREAD

**Issue by lobster2012** [connamara/quickfixn#353]
See this problem
http://stackoverflow.com/questions/9614485/file-existence-check-after-a-folder-rename-returns-an-incorrect-value-on-unc-sha

When filestore call reset func, this func delete files, but system file io exists return true in open func
and streamreader throws UnauthorizedAccessException.
Default cache timeout is 5 sec.

To create this situation - use bad host and port.

solve - insert timeout or not read files after clear files

Thanks (sorry for my pure english)

**Comment by lobster2012-user** [comment]
Any updates?
Problem causes crash of app and happens during frequent reconnects

**Comment by gbirchmeier** [comment]
Closing this very old issue.

If this is still happening, please open a new issue and report your findings based on a current release.
