### ISSUE TITLE
resend requests

### ISSUE THREAD

**Issue by pearljam100** [connamara/quickfixn#355]
Apologies if a repeat...
If anyone can help on this? If i close my fix session say 5pm BST but have sent US and asian orders over night and restart fix next business day at 7am, how do i recover partial and complete fills from previous day? I thought resend request would work but when i use beginning seq # 0 to 9999 i just get all my messages e.g. new orders sent to counterparty. I am sure it is possible but not sure how? thanks.

**Comment by gbirchmeier** [comment]
Not a bug, so closing it.

I saw your mail list mail.  I'm not sure, but I'll see if I can get you an answer.
