### ISSUE TITLE
"Only UTC time is supported" work flow seems inconsistent

### ISSUE THREAD

**Issue by richkeenan** [connamara/quickfixn#367]
I got this error when starting up a session today,

```
Service cannot be started. System.ArgumentException: Only UTC time is supported
Parameter name: oldtime
   at QuickFix.SessionSchedule.IsNewSession(DateTime oldtime_utc, DateTime testtime_utc)
   at QuickFix.Session.get_IsNewSession()
   at QuickFix.Session..ctor(IApplication app, IMessageStoreFactory storeFactory, SessionID sessID, DataDictionaryProvider dataDictProvider, SessionSchedule sessionSchedule, Int32 heartBtInt, ILogFactory logFactory, IMessageFactory msgFactory, String senderDefaultApplVerID)
   at QuickFix.SessionFactory.Create(SessionID sessionID, Dictionary settings)
```

My .session file was all messed up (I think I had multiple instances of Quickfix running, I'm not too worried about that because it was likely user error rather than Quickfix). But this caused the following to happen:
1. `FileStore.InitializeSessionCreateTime()` was called and read my messed up session file
2. `UtcDateTimeSerializer.FromString(s)` was called with corrupt data. This threw an Exception and returned `DateTime.MinValue` as the fallback value.
3. This ended up in `SessionSchedule.IsNewSession` which threw the "Only UTC time is supported (oldtime)" Exception because `DateTime.MinValue` has `Kind=Unspecified` (not UTC).

I think the `DateTime.MinValue` fallback isn't ideal because other parts of the system depend on the value being in UTC. Maybe it should convert this to UTC, or not even bother with a fallback because if the session file is corrupt then we're in big trouble.

Btw, this is not related to #345 because I've only ever used version 1.5

**Comment by DanHarman** [comment]
I'm seeing this error too, and its very misleading as clearly something else is wrong!

**Comment by gbirchmeier** [comment]
Probably a hint of a real issue here, but doesn't sound severe, gonna let it go
