### ISSUE TITLE
Can't parse FIX message containing binary data in RawData field

### ISSUE THREAD

**Issue by ghost** [connamara/quickfixn#372]
It seems that QuickFix/n 1.6.0 can't know how to handle the kind of message below (just an extract for illustrative purposes - see attached files for complete message). Field 96 (RawData) contains a FAST encoded message (binary data).

`(8=FIX.4.49=380335=URDR34=1249=BVMF52=20160216-13:56:28.27656=TSAD000495=100896=���#gs:>����#gs:    a����#gs:L����#gs:o����#gs:Y����#gs:|����...911=1998...)
`

As soon as it receives this message it throws an "QuickFix.MessageParseError: Could not parse message: Error at position (89)" and finishes the FIX session.

[FIX Message File (8kb)](https://github.com/connamara/quickfixn/files/132934/FIX.4.4-TSAD0004-BVMF.messages.20160216115628.txt)
[Fix Event file (7kb)](https://github.com/connamara/quickfixn/files/132935/FIX.4.4-TSAD0004-BVMF.event.20160216115628.txt)

**Comment by gbirchmeier** [comment]
Redundant with #155
