### ISSUE TITLE
The certificate chain was issued by an authority that is not trusted

### ISSUE THREAD

**Issue by cwng2410** [connamara/quickfixn#382]
Hi , I encountered above certificate error during runtime .
Below is my tradeclient_ssl.cfg

SSLEnable=Y
SSLValidateCertificates=N
SSLCertificate=C:\Users\ngcw\Desktop\qfix\quickfixn-master\Examples\TradeClient\QuickFixn-TestClient.pfx
SSLCertificatePassword=xxxxxxx

I had cert and key into TradeClient\QuickFixn-TestClient.pfx.
For the CA certificate,  I had imported into Windows trusted cert .
Please advise why am I still encountering this cert error ?

**Comment by gbirchmeier** [comment]
This sounds like a problem with the certificate, not QF/n.  Where did you get this certificate?

**Comment by cwng2410** [comment]
Hi.Grant,

I got it from bloomberg..it is from their test server.

**Comment by cwng2410** [comment]
Hi Grant,

FYI, I managed use qfix messenger to connect using the same cert, key and
CA cert imported into a javakeystore .
Hence , I thought that the cert, key and CA files should be fine .
Rather, I figuring out how to get the program or environment settings to
accept a cert chain that is not trusted .

On Tue, Feb 23, 2016 at 10:51 PM, Grant Birchmeier <notifications@github.com

**Comment by cwng2410** [comment]
HI Grant,

Thanks a lot , I managed to solve it, my CA cert was not imported correctly
to the PFX file ..

**Comment by gbirchmeier** [comment]
Great, glad you were able to figure it out.
