### ISSUE TITLE
DDMap.AddGroup() adds groups using the wrong tag number

### ISSUE THREAD

**Issue by mfrischknecht** [connamara/quickfixn#384]
This is more of a "lurking bug", since the method itself doesn't seem to be referenced from anywhere else currently; I stumbled upon it simply because I tried to determine what the key value for `DDMap.Groups` should be.

At [DataDictionary/DDMap.cs:24](https://github.com/connamara/quickfixn/blob/2148c0b587cf08c00d018f6a16a906f7899b9541/QuickFIXn/DataDictionary/DDMap.cs#L24) the `DDMap.AddGroup` method inserts a `DDGrp` into the data dictionary definition by using its delimiter field as a key. At the same time, the code at [DataDictionary/DataDictionary.cs:594](https://github.com/connamara/quickfixn/blob/2148c0b587cf08c00d018f6a16a906f7899b9541/QuickFIXn/DataDictionary/DataDictionary.cs#L594) suggests that the according numbering field should be used (this is what actually gets called in the parsing phase).

**Comment by gbirchmeier** [comment]
Not gonna investigate this possible bug without an example of failure
