### ISSUE TITLE
TradeClient - Error Given key is not found in the dictionary

### ISSUE THREAD

**Issue by cwng2410** [connamara/quickfixn#385]
Hi , please refer to my screens in the attachment

FIX_add_parameters.docx](https://github.com/connamara/quickfixn/files/197119/FIX_add_parameters.docx)

**Comment by gbirchmeier** [comment]
I think you didn't create a field definition for 6622, which is NOT a standard FIX field.

The engine sees that you added a field called BenchmarkYield to ExecutionReport, but doesn't know what tag number it is.  It's looking inside the <field> definitions (at the bottom of the DD file) for an entry called BenchmarkYield, but not finding it.  Hence your error.

This does not look like an engine bug, so I am closing it.  In the future, please use the [mailing list](http://quickfixn.org/help/) or StackOverflow for help requests unless you are sure you've found an engine bug.

**Comment by cwng2410** [comment]
HI Grant,

Thanks for your advice. Noted in the future , I will report under mailing
list for issue .

On Thu, Mar 31, 2016 at 11:20 PM, Grant Birchmeier <notifications@github.com

**Comment by cwng2410** [comment]
Hi Grant,

I had added a new 6622 tag number for benchmarkyield,in he fix data
dictionary.
However ever in the tradeclient object, I am unable to access this
attribute under the QuickFix object .
Is there any place else that I need to configure the QuickFix object to
recognize this new attribute ?

[image: Inline image 1]

**Comment by gbirchmeier** [comment]
I assume you're trying to instantiate or access some kind of BenchmarkYield object.  This class will not exist unless you regenerate the fields and messages based on your modified DataDictionary.  (See README).

If you don't want to do that, you can use generic methods like msg.GetString(6622) to get a StringField object.  This is noted at the bottom of http://quickfixn.org/tutorial/custom-fields-groups-and-messages.html

**Comment by cwng2410** [comment]
Thanks for the tip . Grant ..:)
