### ISSUE TITLE
Concern sending AE message

### ISSUE THREAD

**Issue by asinha77** [connamara/quickfixn#386]
I have a initiator setup that works well for sending out J and AK messages. I am trying to use the same session to send AE messages. While attempting to do so, the AE message always picks up the next message string in queue and merges them together before sending it out. Weather its another AE message or even just a heartbeat message. I purposely even put a delay between 2 AE message, but in that case it picks up the heartbeat message before sending it out. pretty weird. Anyone had the same issue or similar? 

if(msg.Header.GetField(35) == "J")
                              {
                                  QuickFix.FIX44.AllocationInstruction oAlloc = new QuickFix.FIX44.AllocationInstruction();
                                  oAlloc.FromString(xMess.FIXMessage, true, dict, dict, _defaultMsgFactory);                                
                                  Session.SendToTarget(oAlloc, session);
                              }
                              else if (msg.Header.GetField(35) == "AK")
                              {
                                  QuickFix.FIX44.Confirmation oConfirm = new QuickFix.FIX44.Confirmation();
                                  oConfirm.FromString(xMess.FIXMessage, true, dict, dict, _defaultMsgFactory);
                                  Session.SendToTarget(oConfirm, session);
                              }
                              else if (msg.Header.GetField(35) == "AE")
                              {
                                  QuickFix.FIX44.TradeCaptureReport oTrdCptRpt = new QuickFix.FIX44.TradeCaptureReport();
                                  oTrdCptRpt.FromString(xMess.FIXMessage, true, dict, dict, _defaultMsgFactory);
                                  Session.SendToTarget(oTrdCptRpt, session);                                  
                              }

That's pretty much all I am doing, while the J and AK section works well.

**Comment by gbirchmeier** [comment]
Please send your help requests to the mailing list or to StackOverflow.  Github Issues are for tracking engine bugs only.

http://quickfixn.org/help/
