### ISSUE TITLE
ObjectDisposedException (FileLog)

### ISSUE THREAD

**Issue by Krakean** [connamara/quickfixn#390]
Hello.
Getting an error when trying to logout (by using _socket.Stop() of SocketInitiator): http://i.imgur.com/ThcKqXX.jpg

This is my setup, if it matters:
            _qfsettings = new SessionSettings(Settings.GetPath());
            _initiator = new Initiator(_qfsettings);
            _msgStoreFactory = new FileStoreFactory(_qfsettings);
            _logFactory = new FileLogFactory(_qfsettings);
            _socket = new SocketInitiator(
                _initiator,
                _msgStoreFactory,
                _qfsettings,
                _logFactory
                );

P.S. I'm using latest Quickfixn master.

**Comment by gbirchmeier** [comment]
Please ask your questions on the mailing list or stackoverflow.  Github is for bug-tracking, not help-asking.  Thanks.

Post your whole exception also.

**Comment by Krakean** [comment]
What's help-asking? I posted you a screenshot link with error and error text in subject + callstack. What else you need? Tell me, i'll try to add other needed details, because in my case this exception is reproducible everytime when I close application.

**Comment by gbirchmeier** [comment]
Sorry, we get a lot of dumb questions on Github that aren't bugs at all, and sometimes I close them too hastily.  I overlooked some details in your post (like your screenshot, duh), and this does look like a real bug.

It appears that something is trying to call a method on a FileLog after it has already been disposed.

That happens every single time?  Does it matter how long your app is open?

**Comment by Krakean** [comment]
>That happens every single time? 
Yep. Have to disable break on ObjectDisposedException.

>Does it matter how long your app is open?
Nope. Just after I did login procedure, and trying to logout by using _socket.Stop().
Also, if you want (in case if error not producible in your case) I can give you TeamViewer access to my PC so you can debug using my PC, i'll just watching :)

**Comment by devfxplayer** [comment]
any update?

**Comment by gbirchmeier** [comment]
addressed by #505
