### ISSUE TITLE
Bug in Message.GetMsgType

### ISSUE THREAD

**Issue by richardcallen** [connamara/quickfixn#391]
There is a bug in the regex for the function Message.GetMsgType(string), line 295 of Message.cs where it will not produce a match if 35 is the first field in the message.

Match match = Regex.Match(fixstring, Message.SOH + "35=([^" + Message.SOH + "]*)" + Message.SOH);

This instead should be altered so that there is a choice between 35 being preceded by SOH or by the start of the message.

Match match = Regex.Match(fixstring, "(^|" + Message.SOH + ")35=([^" + Message.SOH + "]*)" + Message.SOH);

Many thanks,

Richard Allen

**Comment by gbirchmeier** [comment]
A message that starts with "35" is not a valid FIX message.  All FIX messages must start with "FIX." or "FIXT.".

What is the context in which you are passing in messages that start with "35"?

**Comment by richardcallen** [comment]
Hi Greg,
Thanks for the quick response. The context is a set of large FIX data files provided by a major exchange. At the start of each file are a number of lines beginning 35=d (security definition), essentially providing a list of the securities the file contains. As far as I can see in FIX 5.0 there are no mandatory fields in the header, but if you are certain that's not relevant and each line should start with FIX. regardless then I expect it's been omitted for brevity given the context... in which case are you suggesting that the correct fix for me is to prepend each message with FIX.(\u0001) before feeding it into Quickfix?
Thanks,
Richard


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Grant Birchmeier <notifications@github.com> </div><div>Date:12/05/2016  18:16  (GMT+00:00) </div><div>To: connamara/quickfixn <quickfixn@noreply.github.com> </div><div>Cc: richardcallen <richard_clive_allen@hotmail.com>, Author <author@noreply.github.com> </div><div>Subject: Re: [connamara/quickfixn] Bug in Message.GetMsgType (#391) </div><div>
</div>
A message that starts with "35" is not a valid FIX message.  All FIX messages must start with "FIX." or "FIXT.".

What is the context in which you are passing in messages that start with "35"?

---

**Comment by gbirchmeier** [comment]
I misspoke: All messages start with `8=`, and *then* "FIX." or "FIX.T".

If you look at [FIXimate](http://www.fixtradingcommunity.org/FIXimate/FIXimate3.0/) or the FIX specs you'll see that this is *always* the first field of the standard header of any message.

So yes, I'd say that prepending your message with... well, just the `\u0001` (aka `Message.SOH`) character alone would make `Message.GetMsgType(string)` behave.

If you need to use other `Message` functions, or create `Message` objects, you may need to do some other hacks on your exchange's sample messages, such as add BodyLength or alter the CheckSum.  And of course, your XML DataDictionary file needs to match what your exchange is using (they may have made customizations to the standard DD).  It really depends on how much your exchange has messed with those messages.

**Comment by richardcallen** [comment]
Hi Greg,

As far as I can see I don't think that the XML specs for quickfix/n are consistent with what you say. For example, if I look at FIX44.xml then I can see that BeginString i.e. 8 is required in the header, but for FIX50SP2.xml then it is not listed as a required field in the header - in fact, no fields are required in the header. I agree that FIXimate suggests that BeginString is needed even for FIX5.0SP2. How do you explain the apparent difference between the two?

Thanks

Richard

**Comment by gbirchmeier** [comment]
(My first name is Grant, actually.)

The XML docs are not official FIX specs, but regardless, they do support my assertion.  For FIX5, the header is defined in the FIXT11.xml file.  You'll see that tag 8 is indeed included.

For the final word, you should check the official FIX specs at fixtradingcommunity.org, where I guarantee that you will find that FIX strings must always begin with tag 8.  (FIXimate is published by that same group, and I trust that as accurate as well.)

**Comment by richardcallen** [comment]
Hi Grant, 
Sorry about the name - not sure where I thought I saw that. You're completely correct, and by adding the missing tag to the front of the FIX I have managed to get QuickFix to work as expected. Thanks very much for all your assistence.
Richard
