### ISSUE TITLE
Session.SendToTarget Deadlock

### ISSUE THREAD

**Issue by piotrzaremba** [connamara/quickfixn#394]
Under "heavy" load e.g. 1000 messages per second a deadlock occurs when trying to access a single instance of a SessionID from the dictionary.  A possible solutions is to use a concurrent dictionary if the .Net framework can be upgraded to 4.5.2.

**Comment by mrefky** [comment]
I am having the same issue and if you did solve this then Pls.  Send more details on how to resolve this. Thanks.

**Comment by piotrzaremba** [comment]
Hey sorry I did not reply before I got caught up in other work.  I did not come up with a solution but I will into it.

**Comment by mrefky** [comment]
Thanks for help. Waiting for the details.

**Comment by mrefky** [comment]
After the latest windows 10 update, I no longer have that issue. Thanks.

**Comment by piotrzaremba** [comment]
Strange honestly I think this is still a concurrent dictionary / async issue not actually correlated with any windows 10 update.  @GeorgeTsiokos

**Comment by GeorgeTsiokos** [comment]
@piotrzaremba is the deadlock inside `SendRaw` or `SendToTarget` ?

**Comment by piotrzaremba** [comment]
@GeorgeTsiokos it is in the SendToTarget stack.  I just wanted to add you to the issue for reference.  I can't remember what we found before that was causing the deadlock if it was the non concurrent dictionary and/or the threading code.

**Comment by firephantomassasin** [comment]
@piotrzaremba did you encounter this during real market exchange or just by using the mock server of quickfix?

**Comment by piotrzaremba** [comment]
@firephantomassasin the issue was and is being experienced in a mock scenario as well as using live market messaging.

**Comment by firephantomassasin** [comment]
@piotrzaremba have you guys found a fix for your issue? What do you do when it happens during live market?

**Comment by piotrzaremba** [comment]
@firephantomassasin personally I recommend the following:

1) Switch to a commercial engine like B2Bits.
2) Remove the bi-directional design and split up your connection e.g. one for inbound and one for outbound.
3) Switch to the Java version.
4) Patch the .Net code.  

What is your current throughput?  I believe we topped out at 1k bidirectional or 2k unidirectional.

**Comment by gbirchmeier** [comment]
Closing this very old issue.

If this is still happening, please open a new issue and report your findings based on a current release.
