### ISSUE TITLE
Certificate types supported by quickfixn

### ISSUE THREAD

**Issue by sebapi** [connamara/quickfixn#395]
Hi,

What are certificate types supported by quickfixn ?
In some post from 2014 I've read that library supports only PKCS12.
Is it still true or I can use another certificate (e.g. *.crt files).

Thank you
Sebastian

**Comment by geobmx540** [comment]
I haven't tested, but the code looks to use [X509Certificate2](https://msdn.microsoft.com/en-us/library/ms148413(v=vs.110).aspx) which handles both encoding types

> The byte array can be binary (DER) encoded or Base64-encoded X.509 data. 

Seems like it should work just fine (http://info.ssl.com/article.aspx?id=12149)
