### ISSUE TITLE
Please update NuGet package on nuget.org

### ISSUE THREAD

**Issue by msnelling** [connamara/quickfixn#403]
Would it be possible to keep the nuget.org repository up to date with the latest tagged releases?

**Comment by gbirchmeier** [comment]
​The ​nuget package is not official, and we had nothing to do with it.  (We
neither endorse nor oppose it at this time.)

You'll have to follow up with the person who posted it (nuget user
"junvtd").

On Wed, Jul 13, 2016 at 11:03 AM, Mark Snelling <notifications@github.com>
wrote:

> Would it be possible to keep the nuget.org repository up to date with the
> latest tagged releases?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/connamara/quickfixn/issues/403>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAOe6BGei68BdDZVIPEtu215wA5lfa_Kks5qVQw_gaJpZM4JLlGn>
> .
>



-- 
Grant Birchmeier
*Connamara Systems, LLC*
*Made-To-Measure Trading Solutions.*
Exactly what you need. No more. No less.
http://connamara.com

**Comment by msnelling** [comment]
Would you be open to providing an official NuGet package?

**Comment by gbirchmeier** [comment]
We (Connamara) simply don't have much experience with it.  We know a lot about FIX and QuickFIX, but we're not super-deep into the .NET ecosystem.

So I wouldn't say we are "opposed," but it's not really on our priority list.
