### ISSUE TITLE
FieldMap and fields

### ISSUE THREAD

**Issue by vpfau** [connamara/quickfixn#407]
Looking on your FieldMap class I'm wondering - why you provide access to field collection via GetEnumerator() and hide IField in other methods? Like as [here](https://github.com/connamara/quickfixn/blob/master/QuickFIXn/Message/FieldMap.cs#L525)

I need copy a set of tags from one message to another. Is there any efficient way to do this?
At the moment I have to convert everything to string to achieve my goal:

``` c#
        private static void CopyFields(FieldMap source, FieldMap target, params int[] fields)
        {
            foreach (var tag in fields.Where(source.IsSetField))
                target.SetField(new StringField(tag, source.GetField(tag)));
        }
```

of cource I can walk thru IField from GetEnumerator and get the type of field, but I think it will be much better to have IField by tag at FieldMap. If you don't like return the same instance, we can introduce a copy constructor in IField.
Any thoughts?

**Comment by cbusbey** [comment]
Hi there.  This was primarily a port from existing QuickFIX implementations.  We tried to .Netize as much as possible, while keeping the interface as close to the other implementations as possible.  If you would like to submit a PR we would be glad to evaluate.  Thanks
