### ISSUE TITLE
Swallowed/ignored error 

### ISSUE THREAD

**Issue by Rotaerk** [connamara/quickfixn#409]
Using an instance of SocketInitiator with a FileStoreFactory, a FileLogFactory, and a bare-bones IApplication implementation, if I have the RefreshOnLogon setting set to Y, a Logon message is never sent.  The log just indicates that it successfully connects, and nothing further happens.

The reason for this is that the FileStore.Refresh method throws a NotImplementedException, but the SocketInitiator.SocketInitiatorThread method catches and ignores it.  There is a comment saying "It might be the logger ObjectDisposedException, so don't try to log!", but this is _not_ an excuse for quietly swallowing exceptions.  If the logger ObjectDisposedException itself shouldn't be logged, then it should be checked for, and specifically ignored, but everything else should be logged if possible.

**Comment by gbirchmeier** [comment]
Apparently I fixed this in 

https://github.com/connamara/quickfixn/commit/2b0a66e2f3b2995884d772d44deb4680ec2c5578#diff-df64b92e27cabb4109caf7c30247544b

as part of #489 (which is completely unrelated).
