### ISSUE TITLE
Could you please sign your assembly with a strong name signature ? 

### ISSUE THREAD

**Issue by nniched** [connamara/quickfixn#412]

**Comment by IvoTops** [comment]
Yes. My code also requires a strongly signed library. Should be standard (and is done by many) packages on NuGet. Workaround (for me) is downloading from GitHub and signing myself before using...

**Comment by cbusbey** [comment]
That nuget package was created by a user of quickfixn and is not published by the quickfixn maintainers.  We'll note this as a requirement for #248.  Thanks
