### ISSUE TITLE
FileStore.Refresh() being called from Session.NextLogon, but it throws NotImplementedException

### ISSUE THREAD

**Issue by mcmillab** [connamara/quickfixn#423]
On 1 February 2017 at 08:06, Grant Birchmeier <gbirchmeier@connamara.com> wrote:
Woooow.  If you have a moment, please make an issue for that.

In the meantime, it seems clear that RefreshOnLogon should not be used.

> On Tue, Jan 31, 2017 at 2:51 PM, Ben Mcmillan <ben.mcmill@gmail.com> wrote:
> it's not called from my code.
> 
> Session.NextLogon calls Refresh() it RefreshOnLogon is set to true.
> 
> 

> > On 1 February 2017 at 03:25, Grant Birchmeier <gbirchmeier@connamara.com> wrote:
> > You didn't call it from your own code?
> > 
> > If internal QF/n code is calling a not-implemented function, I'd say that's a blunder.
> > 

> > > On Tue, Jan 31, 2017 at 12:42 AM, Ben Mcmillan <ben.mcmill@gmail.com> wrote:
> > > Hi,
> > > 
> > > This method throws a NotImplementedException, for good reason no doubt.
> > > 
> > > Presumably it's not meant to be called - what am I doing wrong such that it is called?
> > > 
> > > Also if I look in latest code at https://github.com/connamara/quickfixn, the static method SocketInitiatorThreadStart seems to catch and report on certain types of errors, but then remaining exceptions are caught at ignored. Is it worthwhile writing something to the log in this case? It took me a while to work out where the error was.
> > > 
> > > thanks
> > > Ben
> > 
> 
> 

>

**Comment by gbirchmeier** [comment]
Same as #433, which is addressed by PR #547
