### ISSUE TITLE
UTF-8 characters can not be show correctly.

### ISSUE THREAD

**Issue by nov30th** [connamara/quickfixn#426]
It seems that once there is an UTF-8 character with multi-byte, the character might be received by separated packages and got incorrect character.

![quickfix problem](https://cloud.githubusercontent.com/assets/11451122/23950719/e4226468-09c6-11e7-9214-cfc68cf491e0.png)
![quickfix problem2](https://cloud.githubusercontent.com/assets/11451122/23951268/98007104-09c8-11e7-8cc5-c65e57d00062.png)

**Comment by gbirchmeier** [comment]
FIX is ASCII.  Other character encodings are only allowed in fields named "Encoded<Something>".

(Some counterparties do send other-encoded characters in non-Encoded fields, but they are wrong.  This is usually not a problem unless the char is multibyte.)

This is tracked by #155, so closing this issue.
