### ISSUE TITLE
QuickFix/n Engine in a real time .Net application

### ISSUE THREAD

**Issue by houssemzitoun** [connamara/quickfixn#432]
Hello Everyone,
I'm trying to implement quickfix/n in a real time multi platform application ( as a project for my engineering degree). 
I thought about using SignalR 2 and a wcf service (to host the quickfix/n engine) to make the system efficient and scalable... But i think may be there is another way... 
Can you propose a better architecture to build a trading solution using Asp.net and Quickfix/n engine ?
I'm really confused guys .
Thank you

**Comment by brobits** [comment]
> Can you propose a better architecture to build a trading solution using Asp.net and Quickfix/n engine ?

The best solution for your project is one that you come up with yourself.  Scaling QuickFIX/n for your degree requirement is a bit off-topic for a GitHub issue.  [Perhaps try asking the mailing list?](http://lists.quickfixn.com/listinfo.cgi/quickfixn-quickfixn.com) Good luck with your solution.
