### ISSUE TITLE
RefreshOnLogon=Y throws NotImplementedException

### ISSUE THREAD

**Issue by brobits** [connamara/quickfixn#433]
QuickFIX/n documentation officially [supports RefreshOnLogon=Y](http://quickfixn.org/tutorial/configuration.html#session).

The flag is loaded from the session settings [here](https://github.com/connamara/quickfixn/blob/63a84b7f488bd3abf2041f7d43c86c35dc51cd05/QuickFIXn/SessionFactory.cs#L109-L110).

The flag is used [in Session.NextLogon](https://github.com/connamara/quickfixn/blob/63a84b7f488bd3abf2041f7d43c86c35dc51cd05/QuickFIXn/Session.cs#L691-L692).

But [Refresh throws a NotImplementedException](https://github.com/connamara/quickfixn/blob/63a84b7f488bd3abf2041f7d43c86c35dc51cd05/QuickFIXn/FileStore.cs#L286), which is silently caught [here](https://github.com/connamara/quickfixn/blob/63a84b7f488bd3abf2041f7d43c86c35dc51cd05/QuickFIXn/Transport/SocketInitiator.cs#L84).

QF/n's behavior is such that the event log records a valid connection, and then goes silent.

I'd suggest either implementing the Refresh() call, or removing documented support for RefreshOnLogon.  Suggestions?

**Comment by gbirchmeier** [comment]
handled by PR #547
