### ISSUE TITLE
98 Tag (Signature) as ReqFields from incoming logon message

### ISSUE THREAD

**Issue by Ales999** [connamara/quickfixn#436]
Hello!
Strange problem, in incoming message, after succesful logon, not included 98 tag and this normal.

Send :  8=FIX.4.49=9535=A34=149=quik52=20170519-21:55:33.91756=StockSharpTS98=0108=30141=Y553=quik554=quik10=204

Receive: 8=FIX.4.49=5935=A49=quik56=StockSharpTS52=20170519-21:55:34.21734=110=085

Check why crash:

![1](https://cloud.githubusercontent.com/assets/367257/26269767/54e496f4-3d10-11e7-97ea-c49b7e440658.png)
![2](https://cloud.githubusercontent.com/assets/367257/26269773/5b1152ba-3d10-11e7-9a52-0df1411e357c.png)
And debug:
![3](https://cloud.githubusercontent.com/assets/367257/26269777/5ef1b5dc-3d10-11e7-8b9f-9e19f77515cc.png)

PS Please sorry for my bad english

**Comment by gbirchmeier** [comment]
This is a help request, not appropriate for a github issue.
