### ISSUE TITLE
Unable to Get Rates By QuoteRequest .. 

### ISSUE THREAD

**Issue by Fatima49** [connamara/quickfixn#441]
Can any one please guide me how can i  get rates by QuoteRequest.. i am using TradeClient with Executor project. Is there is any way to Get Rates .
TIA

**Comment by gbirchmeier** [comment]
Github issues are not for help requests.  Please visit quickfixn.org/help to see the correct channels for questions and support.

Also, check your counterparty's documentation.  QuickFIX does provide messages and fields for Quote retrieval, but all counterparties may use them a little differently depending on their policies.
