### ISSUE TITLE
FIX event    IO Error: IO Error: Unable to get file pointer position from D:\FixStore\FIX.4.4-ABC.body

### ISSUE THREAD

**Issue by SumitGuupta** [connamara/quickfixn#449]
The following are the events identified:
1. Some IO errors due to which Fix engine was unable to get length of fixstore file ( for approx 20 secs).
 	FIX event    IO Error: IO Error: Unable to get file pointer position from D:\FixStore\FIX.4.4-ABC.body

2.  Connection reset error as below:  
               FIX event    Socket Error: Connection reset by peer.

3.  Disconnection error as below:
	FIX event    Disconnecting.

4.  Logon requests:
	FIX event    Logon contains ResetSeqNumFlag=Y, reseting sequence numbers to 1
	FIX event    Received logon request.

On further analysis found that this is due to below piece of code (QuickFix):

int offset = ftell( m_msgFile );
  if ( offset < 0 ) 
    throw IOException( "Unable to get file pointer position from " + m_msgFileName );

But I am not able to find out actual reason why it happened.

Could anyone help me out how I could resolve this issue.

**Comment by gbirchmeier** [comment]
"ftell"?  That's not C#, that's C.

I think this report is posted for the wrong project.
