### ISSUE TITLE
Missing TimeStampPrecision constructor in DateTimeField

### ISSUE THREAD

**Issue by fiskalna123** [connamara/quickfixn#455]
Hello,

we had some issues using latest version of QuickFix generator - generated code would not build because of missing constructors in DateTimeFields for newly introduced TimeStampPrecision enum.
We added following line in ruby code gen_fields.rb, ln 114 (date fields creation)

public #{field[:name]}(#{field[:base_type]} val, TimeStampPrecision timestampPrecision)
	    :base(Tags.#{field[:name]}, val, timestampPrecision) {}

Please update Your ruby code (or tell us if we did something wrong)

**Comment by DSolimano** [comment]
Looks right to me - I'll send in a pr

**Comment by gbirchmeier** [comment]
Not sure when this was fixed, but I see these constructors in generated code now
