### ISSUE TITLE
FIX50 SP2 namespace

### ISSUE THREAD

**Issue by j492** [connamara/quickfixn#456]
using Quickfix.FIX50SP2; 
I am using quickfixn 1.7 and the namespace for sp2 is not there. The repository shows the classes in the sp2 folder. There are namespaces for 4.4 to 5.0 except sp1 and sp2. 
How can I get the classes for 5.0 sp2?
I appreciate your help and like to use sp2 if I can.

**Comment by gbirchmeier** [comment]
Pretty sure this got sorted out.  Anyway, this is a help request, not appropriate for an issue.
