### ISSUE TITLE
Not receiving logout message FIX 4.2

### ISSUE THREAD

**Issue by devoju** [connamara/quickfixn#458]
Hi,

I'm receiving a logon message when I should receive a logout message.
The cause of this issue is that I'm not receiving a logout message first, so the sender disconnects and QuickFix tries to login again, hence the login message.

Below are the logs:

Session FIX.4.2 disconnecting: System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at QuickFix.SocketInitiatorThread.ReadSome(Byte[] buffer, Int32 timeoutMilliseconds)
   at QuickFix.SocketInitiatorThread.Read()
Connecting to ip on port 
Connection succeeded
Initiated logon request
Received logon

Anyone knows the cause of this issue?
Thanks

**Comment by DSolimano** [comment]
It looks more like your counterparty crashed, and the retry logic got you back in good order.  Was the session supposed to be offline?

**Comment by LittleAlexey** [comment]
Thanks, same (or very close to) issue i have. Lib receives clear logout message, something like (from FIX logs)

20180118-16:52:03.590 : 8=FIX.4.4|9=0103|35=5|34=00000022|52=20180118-16:52:03.088|49=111|56=222|58=Invalid Username|10=114|

This I expected to receive in my OnMessage(Logout message, SessionID sessionID) from the Crack, but never receive it.
Lil more strings from event file:
20180118-16:52:03.449 : Initiated logon request
20180118-16:52:03.591 : Session FIX.4.4:222->111:Price disconnecting: Received msg type '5' when not logged on
20180118-16:52:03.594 : Session reset: ResetOnDisconnect

Message often contains important information for user like invalid tags specified, expiration of account, etc.

**Comment by LittleAlexey** [comment]
yeah, maybe important that this Logout message i receive as answer for my logon message with incorrect (for the server part) params

**Comment by LittleAlexey** [comment]
Sorry, this is not the same issue at all...
Think that this thread should be closed since receiving logout message from server when it forcibly disconnects is impossible. Looks like the server side issue if it closes socket before sending clear logout answer for logout from client side.
My issue I'll move to the other thread https://github.com/connamara/quickfixn/issues/466
