### ISSUE TITLE
msg.ToString() will reorder the items inside repeating group, (potentially) causes rejection

### ISSUE THREAD

**Issue by akking** [connamara/quickfixn#460]
If we don't generate the FIX Message class for customized data dictionary, `message.ToString()` will not honor the order of the items inside repeating group but default to the pre-generated ones when serialized the `Message` obj into string. When [NextQueued() ](https://github.com/connamara/quickfixn/blob/master/QuickFIXn/Session.cs#L1611) method called `NextMessage(msg.ToString())`, the subsequent call for `Message.FromString(str)` will fail since the "first item for the repeating group is not as expected` and then throw rejection to the counterpart.

We may need to add a new overloaded `NextMessage(Message queuedMsg)` method for `Session` class to handle above situation.

**Comment by gbirchmeier** [comment]
This is known behavior, and there are no plans to change it.  It's highly recommended to generate code anyway.  A future doc revision will stress that more.
