### ISSUE TITLE
Heartbeat in response to TestRequest not being acknowledged FIX 5.0 SP2

### ISSUE THREAD

**Issue by devoju** [connamara/quickfixn#462]
Hey,

I currently have a problem after logon.
I'll get a test request from the provider and quickfix answers with an heartbeat with the correct testreqid but the provider is not acknowledging it. The provides closes the connection at the end of the heartbeat interval.
The only difference I can see at the moment that maybe is causing the problem is that the fields in the messages incoming from the provider have the following order: 49= 56= 52= while the messages outgoing to the provider have a different order: 49= 52= 56= .
I've tried to change the order of the header fields, but haven't got it to work, how can I do this?
Or do you have any idea if it might be something else?

Regards,

**Comment by gbirchmeier** [comment]
Appears to be help request and not a bug.

http://quickfixn.org/help/
