### ISSUE TITLE
Parsing logon message fails on dotnet core running on linux

### ISSUE THREAD

**Issue by jmazar** [connamara/quickfixn#465]
I am trying to use the QuickFix.Net.NetStandard nuget package to run quickfix\n on linux. However I receive the error 
"QuickFix.MEssageParseError Could not parse message: Error at position (3) while parsing msg <msg here>
at System.Number.StringToNumber
at System.Number.ParseInt32
at QuickFix.Message.ExtractField"

I have been able to locate the issue and have a small reproduction. The problem is in the ExtractField method where you call `int fieldvalend = msgstr.IndexOf("\u0001", pos);`. I found while running this on linux dotnet core 2.0+ this fails and returns a value of 2 for  the logon message instead of the correct 9. If I change the "\u0001" to be in single quotes '\u0001' this seems to resolve the problem. I was not able to figure out how to rebuild the package for .net standard from the source code.

I am not sure if there is a different workaround from the .net core end but I have not seen anything. Please let me know if you have more questions or a any ideas on how I could fix this.

Thank you!

**Comment by akking** [comment]
Yes, #448 solved this problem.

**Comment by jmazar** [comment]
Awesome! When/how will I be able to use this?

**Comment by Kedr91** [comment]
Hi there; i have the same issue in Mac osx Mojave and Linus Elementary; i compliled the source following ypur instructions and installing Ruby, but what i get is a lot of little quickfix.dll; how to get the complete almost 20MB dll file? many thanks.

**Comment by gbirchmeier** [comment]
QF/n is no longer one giant dll containing the core and all 6 message-dictionaries.

Now it's 2 dlls:

1) QuickFix.dll
2) QuickFix.FIX<NN>.dll (where NN is one of {41, 42, 43, 44, 50, 50SP1, 50SP2})

So, look in e.g. `Messages\FIX44\bin\Release\netstandard2.0\` and grab the 2 dlls in there.

**Comment by Kedr91** [comment]
> QF/n is no longer one giant dll containing the core and all 6 message-dictionaries.
> 
> Now it's 2 dlls:
> 
> 1. QuickFix.dll
> 2. QuickFix.FIX.dll (where NN is one of {41, 42, 43, 44, 50, 50SP1, 50SP2})
> 
> So, look in e.g. `Messages\FIX44\bin\Release\netstandard2.0\` and grab the 2 dlls in there.

Ahhhhhh now it's clear: done, it works like a charm now in windows, Mac and Linux.
Thank you so much; may i ask you when you plan to release the 1.9.0 version?
cheers.

**Comment by gbirchmeier** [comment]
Haha, I am literally working on deploying 1.9 right now.  Hopefully within an hour or 2.

**Comment by Kedr91** [comment]
> Haha, I am literally working on deploying 1.9 right now. Hopefully within an hour or 2.

wow...perfect timing :-)
happy deploying.
Bye and thanks again
