### ISSUE TITLE
No chance to receive Logout from server when it sends it as first message.

### ISSUE THREAD

**Issue by LittleAlexey** [connamara/quickfixn#466]
Shortly. When client sends Logon with incorrect params (example: incorrect login/password, or sender/target), server usualy sends Logout message as answer.

Lib on client side receives clear logout message, something like (from FIX logs)

20180118-16:52:03.590 : 8=FIX.4.4|9=0103|35=5|34=00000022|52=20180118-16:52:03.088|49=111|56=222|58=Invalid Username|10=114|

This I expected to receive in my OnMessage(Logout message, SessionID sessionID) from the Crack, but never receive it.
Lil more strings from event file:
20180118-16:52:03.449 : Initiated logon request
20180118-16:52:03.591 : Session FIX.4.4:222->111:Price disconnecting: Received msg type '5' when not logged on
20180118-16:52:03.594 : Session reset: ResetOnDisconnect

Message often contains important information for user like invalid tags specified, expiration of account, etc.

**Comment by cyphersys** [comment]
Hello, this issue is occurring in FIX 5.0 SP2 too.

Thank you!

Best regards

**Comment by gbirchmeier** [comment]
fixed by PR #467
