### ISSUE TITLE
Message rejected due to invalid value, FIX 5.0

### ISSUE THREAD

**Issue by antrodrigo23r** [connamara/quickfixn#468]
Hi,

I'm made a few changes to have time fields in nanoseconds, and also pulled #459 changes.
Sometimes it will only return 6, 7 or 8 digits instead of 9, causing the message to be rejected.
E.g.: 

52=20180122-11:16:31.627400

I think the way the nanoseconds are being calculated has some bug.

**Comment by gbirchmeier** [comment]
There's really not much to go on here.  Logs at least would be nice.
