### ISSUE TITLE
Message corrupted by unnecessary UTF8 decoding/encoding

### ISSUE THREAD

**Issue by amichair** [connamara/quickfixn#478]
The SocketInitiatorThread.Read() implementation reads some bytes from the incoming stream into a byte array, then for some reason converts it to a string using UTF8:

```
int bytesRead = ReadSome(readBuffer_, 1000);
if (bytesRead > 0)
    parser_.AddToStream(System.Text.Encoding.UTF8.GetString(readBuffer_, 0, bytesRead));
```

However the very next statement that is executed, in Parser.AddToStream, does the inverse:

```
byte[] bytes = System.Text.Encoding.UTF8.GetBytes(data);
AddToStream(ref bytes, bytes.Length);
```

And the re-encoded bytes are added to the parser's stream.

This is obviously a totally unnecessary round-trip conversion that wastes cpu cycles and memory and generates garbage, and could be trivially eliminated.

However, other than a low-hanging performance issue, this also corrupts messages: if a message contains any non-ASCII data using any multibyte encoding (e.g. in an EncodedText field, even if it is encoded using UTF8), then occasionally the batch of bytes read into the buffer will happen to be cut in the middle of a multibyte character, so the decoding/encoding round-trip will result in the bytes being corrupted by the conversions of invalid half-chars and thus corrupting the whole message.

The trivial solution to both issues is simply to eliminate the conversion, and just use the overloaded Parser.AddToStream method that accepts the read bytes directly.

**Comment by danielshrem** [comment]
We are expiriencing the same issue when it comes to multi byte chars set properly in EncodedText field.
At least in v 1.7.0 the bodylength checksum validation check could be configured to N (so at least u dont get disconnected, but data is still lost).
Anyways re parsing i'de look to quickfixj for inspiration (detecting the header,trailer,body), Its handled properly.
Be happy to help in any way and solve this issue (popping all over) once and for all.

**Comment by gbirchmeier** [comment]
This is the part where I remind everyone that this is an open-source project.  

Did you submit a PR?  Please link to it.

Or if you would like to fund a fix, please use the [Contact Form](http://quickfixn.org/about/contact/) and Connamara will get back to you soon to discuss terms.

If you want it for free, you'll need to wait for one of the project's skilled developers to find time to volunteer to fix it in their free time.

**Comment by gbirchmeier** [comment]
#531 changed the internal character encoding to iso-8859-1 (aka latin1), so latin characters should work fine with the next release.

I just removed the unnecessary ronud trip conversion with PR #537
