### ISSUE TITLE
QuickFix.Net.NetStandard 1.7.9 - cannot read fix log -> getting sharing violation

### ISSUE THREAD

**Issue by 123g** [connamara/quickfixn#479]
When we try to open the fix log file while the app is running, we are getting error "encountered a sharing violation while accesing FIX.4.4...messages.current.log".  All runs on Windows.

QuickFix.Net 1.8.0 is fine ie we can open the fix log files.

Thanks

**Comment by mrefky** [comment]
Try using Snaketail ; it will work and does auto refresh of the logs

**Comment by gbirchmeier** [comment]
This nuget package was not created by us and is not officially supported.  It is also probably not built in the most recent version of the code.

Issue closed.
