### ISSUE TITLE
Warning NU1701

### ISSUE THREAD

**Issue by herme063** [connamara/quickfixn#484]
Hello,

I get the NU1701 warning message in vs 2017 when I add the QuickFix,Net 1.8.0 package to a .NET Core Console project. 

`Package 'QuickFix.Net 1.8.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.`

Is it safe to ignore this warning or is there a workaround to fix it?

Thank you,

**Comment by gbirchmeier** [comment]
The nuget package is not official.  It was not created by us and is not supported by us.  You'll need to reach out to the people that created it.

**Comment by filip-seedcx** [comment]
@gbirchmeier I see. I think it would help the community to have an official nuget package. That would lower the barrier to entry. #248
