### ISSUE TITLE
Nuget Package doesn't support PackageReference structure

### ISSUE THREAD

**Issue by adam-stewart-reddeer** [connamara/quickfixn#488]
Can you update the NuGet package so that it supports the PackageReference structure, and tooling in VS.  Currently, using v1.8.0 VS will return a Package Compatibility Issue : "The assembly 'lib\lib\QuickFix.dll will be ignore when the package is installed after the migration".

**Comment by gbirchmeier** [comment]
The NuGet package was put together by a third party, and is not maintained or supported by us.
