### ISSUE TITLE
Hi, this error returns on Streambase, can you help me?

### ISSUE THREAD

**Issue by muazcoban** [connamara/quickfixn#503]
20181102-08:12:59: Session FIX.4.4:initiator4ID->acceptor4ID schedule is daily, 00:00:00 UTC - 23:59:59 UTC (daily, 00:00:00 UTC - 23:59:59 UTC)
20181102-08:12:59: Created session: FIX.4.4:initiator4ID->acceptor4ID
20181102-08:13:00: Initiated logon request
20181102-08:13:00: Error during message processing
quickfix.SessionException: Tried to send a reject while not logged on: Required tag missing (field 141)
	at quickfix.Session.generateReject(Session.java:1174)
	at quickfix.Session.next(Session.java:850)
	at quickfix.mina.ThreadPerSessionEventHandlingStrategy$MessageDispatchingThread.run(ThreadPerSessionEventHandlingStrategy.java:108)

20181102-08:13:11: Timed out waiting for logon response
20181102-08:13:11: Disconnecting
20181102-08:13:31: Connection refused: no further information
20181102-08:14:01: Connection refused: no further information

**Comment by muazcoban** [comment]
# this is my initiator config
[default]
BeginString=FIX.4.4
ConnectionType=initiator
ResetOnLogon=N
ResetSeqNumFlag=N
StartTime=00:00:00
EndTime=23:59:59
DefaultApplVerID=FIX.5.0
AppDataDictionary=FIX44.xml

[session]
SenderCompID=initiator4ID
TargetCompID=acceptor4ID
SocketConnectHost=10.19.9.134
SocketConnectPort=25008
HeartBtInt=30
FileLogPath=logs/tradairpair
FileStorePath=store/tradairpair

#
# User login properties
#
Username=demo
EncryptedMethod=NONE
ResetSeqNumFlag=Y
Password=demo123
UserOrganization=ARCdemo

**Comment by muazcoban** [comment]
# and this is my acceptor config
[default]
BeginString=FIX.4.4
ConnectionType=acceptor
ResetOnLogon=N
ResetSeqNumFlag=N
StartTime=00:00:00
EndTime=23:59:59
DefaultApplVerID=FIX.5.0
AppDataDictionary=FIX44.xml

[session]
SenderCompID=acceptor4ID
TargetCompID=initiator4ID
SocketAcceptPort=25008
HeartBtInt=30
FileLogPath=logs/tradairpair
FileStorePath=store/tradairpair

#
# User login properties
#
Username=demo
EncryptedMethod=NONE
ResetSeqNumFlag=Y
Password=demo123
UserOrganization=ARCdemo

**Comment by gbirchmeier** [comment]
Please don't submit help requests as issues.  This is for bug tracking only.

For avenues of help, see http://quickfixn.org/help/
