### ISSUE TITLE
Would you officially support nuget ?

### ISSUE THREAD

**Issue by wsq003** [connamara/quickfixn#506]
Nuget is more and more popular recently. It would be greate if there is an offical package in nuget, so that users can get it easily.

**Comment by gbirchmeier** [comment]
We probably will do this in the future.

However, given that nearly all counterparties use custom DataDictionaries, it's highly recommended that all users generate new Message/Field sets based on their DDs and use a custom build.  There are plans to improve ease of codegen and documentation regarding this.
