### ISSUE TITLE
web interface crash

### ISSUE THREAD

**Issue by mrefky** [connamara/quickfixn#510]
when more than 5 sessions are configured and the web interface is browsed using Firefox; and you refresh the page; the web interface crashes and is no longer accessible unless you restart the application. 
when the browser is Microsoft Edge everything works as expected and the crash does not happen.

**Comment by gbirchmeier** [comment]
Seems browser-dependent.  It's possible that our interface is not efficient, but no one's ever complained about it before.  I'm barely aware this feature even exists!  Never used it!

Closing this issue for lack of interest/importance.  Will only pursue if someone on the outside wants to do some investigating.
