### ISSUE TITLE
Tag appear more than once (Field=769)  with trying to parse MarketDataSnapshotFullRefresh

### ISSUE THREAD

**Issue by UtilidexIsha** [connamara/quickfixn#514]
Getting Tag appears more than once (Field=769)  with trying to parse MarketDataSnapshotFullRefresh with or without data dictionary.

Please help ASAP.

**Comment by gbirchmeier** [comment]
Ask on the mailing list, or google your error message.  (I've helped with this kind of problem about a dozen times on StackOverflow.)

Github is not for help requests.  Closing issue.
