### ISSUE TITLE
Cracking Allocation Instruction messages doesn't handle custom fields in allocation account block

### ISSUE THREAD

**Issue by briankavanaugh** [connamara/quickfixn#515]
We have simulator to handle various scenarios to return specific responses for testing, and it is failing to handle custom fields in the allocation accounts block. We are including tags 5751 and 5752 (for VSP information) per account like the below message. When it processes it, it either (a) fails (using the .NET 4.6x version) with an error "field not found for tag: 78", or (b) returns only one of the allocation block sections (.NET Core version).

Message: 

8=FIX.4.49=38935=J49=ORIONDEV56=FLYERDEV57=OASBROKER115=TEST6=1022=148=0ZVZZT88653=754=255=ZVZZT60=20190227-09:57:10.00063=070=100.850071=075=20190227626=2857=173=111=8500.2440.038=7799=1078=379=1058470580=3161=Unsolicited5751=2018-02-08 00:00:005752=179=1058470580=2161=Unsolicited5751=2019-02-12 00:00:0079=1012586780=2161=Unsolicited5751=2018-02-08 00:00:005752=110=105

**Comment by gbirchmeier** [comment]
Did you add those fields to your xml data dictionary?

**Comment by gbirchmeier** [comment]
Also, please join the mailing list or use StackOverflow.  Github is for tracking bugs, not help requests.

**Comment by briankavanaugh** [comment]
@gbirchmeier they are, but I will follow up elsewhere.

**Comment by gbirchmeier** [comment]
I highly recommend the mailing list.  It's not very noisy.
