### ISSUE TITLE
SessionScheduleFactory

### ISSUE THREAD

**Issue by ipetrushevskiy** [connamara/quickfixn#517]
Hello, we really need to customize SessionSchedule implementation from SessionID to SessionID. The reason for ex. - I would like to use daily sessions but disable them for some periods of time on weekends and like that. It seems not hard to contribute and I am even ready to do that (extract interface, rename current implementation to default and add and use appropriate factory). If I do - how soon approximately nuget package with those changes will be published?

**Comment by gbirchmeier** [comment]
The Nuget package is not official.  We did not create it.

We are open to PRs, and your suggestion is something that people have asked for in the past.

I'm closing this issue, as it is not a feature we're officially planning.  But if you code it and want to submit it, we'll gladly consider it.
