### ISSUE TITLE
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ArvindSinghMCA** [connamara/quickfixn#520]
Hi,

I am trying to connect Nodal Exchange using quickfix Api,but I am getting below error.
Could you please help to resolve this issue.

Thanks in Advance !

20190430-15:27:39.571 : Connecting to 4.34.102.152 on port 9883
20190430-15:27:40.206 : Connection succeeded
20190430-15:27:40.208 : Initiated logon request
20190430-15:27:40.609 : Session FIXT.1.1:sna_test_admin/sna_test_admin->Nodal Exchange, LLC disconnecting: System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at QuickFix.SocketInitiatorThread.ReadSome(Byte[] buffer, Int32 timeoutMilliseconds)
   at QuickFix.SocketInitiatorThread.Read()

Thanks and Regards,
Arvind Singh

**Comment by gbirchmeier** [comment]
This does not look like a bug.  Please ask for help on the mailing list or StackOverflow.

**Comment by maylin2019** [comment]
Hi Arvind,
Have you ever found out the cause of the problem and more importantly the solution of the problem?
I am asking because I encountered the exactly same problem recently.
Your feedback is appreciated.
Michael Zhu

**Comment by mrefky** [comment]
Looks like sequence number was less than expected. Try to reset sequence numbers with your login message reset sequence flag
