### ISSUE TITLE
DDMap cannot be build out of a message containing two components with a same group name

### ISSUE THREAD

**Issue by santiagoribero** [connamara/quickfixn#528]
Example case:

```xml
<fix major="5" minor="0">
  <header/>
  <trailer/>
  <messages>
    <message name="AllocationReport" msgtype="AS" msgcat="app">
      <component name="TrdInstrmtLegGrp" required="N"/>
      <component name="InstrmtLegAllocGrp" required="N"/>
    </message>
  </messages>
  <components>
    <component name="TrdInstrmtLegGrp">
      <group name="NoLegs" required="N">
            <field number="654" name="LegRefID" required="N"/>
      </group>
    </component>
    <component name="InstrmtLegAllocGrp">
      <group name="NoLegs" required="N">
            <field number="1400" name="EncryptedPasswordMethod" required="Y"/>
      </group>
    </component>
  </components>
  <fields>
    <field number="555" name="NoLegs" type="NUMINGROUP"/>
    <field number="654" name="LegRefID" type="STRING"/>
    <field number="1400" name="EncryptedPasswordMethod" type="INT"/>
  </fields>
</fix>
```

As you can see, the message “AllocationReport” contains two components, both containing the group “NoLegs” (555), although the groups have different content.
QuickFix tries to create a DDMap per message, containing (in its “Groups” property) all the groups from all the components of the message.
When it has to create the DDMap for the “AllocationReport” message:
1)	it processes the component “TrdInstrmtLegGrp” and inserts the group “NoLegs” to the dictionary, with key 555.
2)	It processes the component “InstrmtLegAllocGrp” and tries to insert its “NoLegs” group, but the dictionary already contains the key 555, therefore an Exception is thrown.

```csharp
else if(childNode.Name == "group")
{
    DDField fld = FieldsByName[childNode.Attributes["name"].Value];
    DDGrp grp = new DDGrp();
    XmlAttribute req = childNode.Attributes["required"];
    if (req != null && req.Value == "Y"
    && (componentRequired == null || componentRequired.Value == true))
    {
        ddmap.ReqFields.Add(fld.Tag);
        grp.Required = true;
    }
    if (!ddmap.IsField(fld.Tag))
    {
        ddmap.Fields.Add(fld.Tag, fld);
    }
    grp.NumFld = fld.Tag;
    parseMsgEl(childNode, grp);
    ddmap.Groups.Add(fld.Tag, grp); //########### It fails when the second component is processed ###########
}
```

**Comment by gbirchmeier** [comment]
This is a known issue, #495.
https://github.com/connamara/quickfixn/issues/495

Your code diagnosis is a little different than mine, but it all stems from the same flawed design.   The original writers simply didn't plan for this to ever happen.

I'm going to close this as dupe, but I'll make a note in the other issue to refer to your code findings here.
