### ISSUE TITLE
Latest code has these compile issues

### ISSUE THREAD

**Issue by acrigney** [connamara/quickfixn#530]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.GetSupportedBeginStrings()'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX42\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.Create(string, ApplVerID, string)'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX42\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.GetSupportedBeginStrings()'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX43\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.Create(string, ApplVerID, string)'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX43\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.GetSupportedBeginStrings()'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX44\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.Create(string, ApplVerID, string)'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX44\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.GetSupportedBeginStrings()'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX50SP1\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.Create(string, ApplVerID, string)'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX50SP1\MessageFactory.cs	7	Active
Error	CS0542	'SecurityStatus': member names cannot be the same as their enclosing type	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX50SP1\SecurityStatus.cs	1351	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.GetSupportedBeginStrings()'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX50SP2\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.Create(string, ApplVerID, string)'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX50SP2\MessageFactory.cs	7	Active
Error	CS0542	'SecurityStatus': member names cannot be the same as their enclosing type	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX50SP2\SecurityStatus.cs	1351	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.GetSupportedBeginStrings()'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX50\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.Create(string, ApplVerID, string)'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX50\MessageFactory.cs	7	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	QuickFix.FIX40(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX40\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	QuickFix.FIX41(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX41\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	QuickFix.FIX42(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX42\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	QuickFix.FIX43(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX43\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	QuickFix.FIX44(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX44\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	QuickFix.FIX50(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX50\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	QuickFix.FIX50SP1(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX50SP1\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	QuickFix.FIX50SP2(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX50SP2\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX40\bin\Debug\netstandard2.0\QuickFix.FIX40.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX41\bin\Debug\netstandard2.0\QuickFix.FIX41.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX42\bin\Debug\netstandard2.0\QuickFix.FIX42.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX43\bin\Debug\netstandard2.0\QuickFix.FIX43.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX44\bin\Debug\netstandard2.0\QuickFix.FIX44.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX50\bin\Debug\netstandard2.0\QuickFix.FIX50.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX50SP1\bin\Debug\netstandard2.0\QuickFix.FIX50SP1.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX50SP2\bin\Debug\netstandard2.0\QuickFix.FIX50SP2.dll' could not be found	AcceptanceTest(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\AcceptanceTest\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	Examples.Executor(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\Executor\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX40\bin\Debug\netstandard2.0\QuickFix.FIX40.dll' could not be found	Examples.Executor(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\Executor\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX41\bin\Debug\netstandard2.0\QuickFix.FIX41.dll' could not be found	Examples.Executor(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\Executor\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX42\bin\Debug\netstandard2.0\QuickFix.FIX42.dll' could not be found	Examples.Executor(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\Executor\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX43\bin\Debug\netstandard2.0\QuickFix.FIX43.dll' could not be found	Examples.Executor(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\Executor\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX44\bin\Debug\netstandard2.0\QuickFix.FIX44.dll' could not be found	Examples.Executor(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\Executor\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX50\bin\Debug\netstandard2.0\QuickFix.FIX50.dll' could not be found	Examples.Executor(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\Executor\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	Examples.SimpleAcceptor(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\SimpleAcceptor\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	Examples.TradeClient(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\TradeClient\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX44\bin\Debug\netstandard2.0\QuickFix.FIX44.dll' could not be found	Examples.TradeClient(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\Examples\TradeClient\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\bin\Debug\netstandard2.0\QuickFix.dll' could not be found	UnitTests(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX40\bin\Debug\netstandard2.0\QuickFix.FIX40.dll' could not be found	UnitTests(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX42\bin\Debug\netstandard2.0\QuickFix.FIX42.dll' could not be found	UnitTests(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX43\bin\Debug\netstandard2.0\QuickFix.FIX43.dll' could not be found	UnitTests(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX44\bin\Debug\netstandard2.0\QuickFix.FIX44.dll' could not be found	UnitTests(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Projects\quickfixn-master\quickfixn-master\Messages\FIX50\bin\Debug\netstandard2.0\QuickFix.FIX50.dll' could not be found	UnitTests(netcoreapp2.0)	C:\Projects\quickfixn-master\quickfixn-master\UnitTests\CSC	1	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.GetSupportedBeginStrings()'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX40\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.Create(string, ApplVerID, string)'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX40\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.GetSupportedBeginStrings()'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX41\MessageFactory.cs	7	Active
Error	CS0535	'MessageFactory' does not implement interface member 'IMessageFactory.Create(string, ApplVerID, string)'	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\Message\FIX41\MessageFactory.cs	7	Active
Error	CS0579	Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\obj\Debug\netstandard2.0\QuickFix.AssemblyInfo.cs	14	Active
Error	CS0579	Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\obj\Debug\netstandard2.0\QuickFix.AssemblyInfo.cs	15	Active
Error	CS0579	Duplicate 'System.Reflection.AssemblyCopyrightAttribute' attribute	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\obj\Debug\netstandard2.0\QuickFix.AssemblyInfo.cs	16	Active
Error	CS0579	Duplicate 'System.Reflection.AssemblyDescriptionAttribute' attribute	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\obj\Debug\netstandard2.0\QuickFix.AssemblyInfo.cs	17	Active
Error	CS0579	Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\obj\Debug\netstandard2.0\QuickFix.AssemblyInfo.cs	18	Active
Error	CS0579	Duplicate 'System.Reflection.AssemblyProductAttribute' attribute	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\obj\Debug\netstandard2.0\QuickFix.AssemblyInfo.cs	20	Active
Error	CS0579	Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\obj\Debug\netstandard2.0\QuickFix.AssemblyInfo.cs	21	Active
Error	CS0579	Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute	QuickFix(netstandard2.0)	C:\Projects\quickfixn-master\quickfixn-master\QuickFIXn\obj\Debug\netstandard2.0\QuickFix.AssemblyInfo.cs	22	Active

**Comment by gbirchmeier** [comment]
I literally just built it right now.  No issues.
