### ISSUE TITLE
How to let quickfix/n support microseconds on datetime?

### ISSUE THREAD

**Issue by Giten2004** [connamara/quickfixn#544]
This microseconds timestamp precision is required by MIFIDII, and MIFIDII has been effective since Jan 2018.

I only find a configuration "MillisecondsInTimeStamp" to let the session support Milliseconds. But do not find how to let it support microseconds.

eg on tag: 

SendingTime (Tag 52),TransactTime (Tag 60),
--

**Comment by Giten2004** [comment]
{code}
TimeStampPrecision=Microsecond
{code}

**Comment by gbirchmeier** [comment]
I guess user answered his own question?
