### ISSUE TITLE
QuickFix.Message loses tags without a datadictionary and calculates body length incorrectly

### ISSUE THREAD

**Issue by rmay-tws** [connamara/quickfixn#545]
QuickFix.Message loses tags from groups when a data dictionary is not present.  Not only that, but it also calculates the body length incorrectly when it loses the tags.

This causes problems for the session, since the body is significantly shorter than expected resulting in the receiver side of the session combining messages to get the expected length since Send(Message) uses Message.ToString() when calling SendRaw() internally.  

In the following example note how the body length is LONGER than the entire string returned by ToString().

Here's an example:

```          
var messageString =
                "8=FIX.4.4|9=284|35=X|34=1311689|49=ABC|52=20190909-15:32:56.753|56=XYZ|268=1|279=1|269=0|278=25395741|55=02051QHT6|48=02051QHT6|22=1|460=3|270=97.267|271=1111|110=2|64=20190911|236=-999.0|887=3|888=INC|889=1|888=MBR|889=0|888=PARTICIPANTS|889=730,237,706,228,377,133,714,5761,774,787,203|10=152|"
                    .Replace('|', (char)01);

            Console.WriteLine($"Input message: {messageString}");
            Console.WriteLine($"Input length: {messageString.Length}");

            QuickFix.Message message = new QuickFix.Message(messageString, false);

            var outputString = message.ToString();

            Console.WriteLine($"Stated body length of message after ToString(): {message.Header.GetField(9)}");

            Console.WriteLine($"Length of message emitted by ToString(): {outputString.Length}");

            Console.WriteLine($"Outputted message string: {outputString}");
```

**Comment by gbirchmeier** [comment]
This message has repeating groups in it.  It is impossible to parse repeating groups without a DataDictionary, because the parser has no idea when each group ends and begins.

Without a DD, the parser assumes each field can only appear once, and the internal storage is a hashmap keyed by tag.  Every occurrence of, for example, 888 will clobber the previous one.  The body length is incorrect because the parser is forgetting all but the final 888 and 889 fields.

There is never a good reason to not use a DataDictionary.  (If I was starting QF/n anew, I would simply not allow a no-DD mode.)

I'm going to close this issue, but feel free to reply if you have a follow-up question.

**Comment by rmay-tws** [comment]
At a minimum, shouldn't the BodyLength value be correct (i.e. ignore the RepeatedFields collection in its calculation)?  This actually caused the receiving side to fail, not the sending side, because when it tried to read from the Stream buffer, the body length caused it to overflow into the next message?  We spent 3 days trying to figure out why messages were being doubled and then exploding.

And I agree--I wish that Message constructor didn't exist. :)

**Comment by rmay-tws** [comment]
Honestly, we'd be happy with an exception if repeating fields were discovered and no data dictionary was present.

**Comment by gbirchmeier** [comment]
> shouldn't the BodyLength value be correct (i.e. ignore the RepeatedFields collection in its calculation)?

In short, QF/n isn't architected for this.  A Message object does not store the full message string that you gave it; actually your message is decomposed into a tag/value HashMaps.  When you access the bodyLength or checkSum, those are computed on the fly.  When you convert it to string, that is also computed on the fly (newbies are often wondering by top-level body fields are re-ordered; this is why).

Just... use a DataDictionary.  Always.

> an exception if repeating fields were discovered and no data dictionary was present

That's not a bad idea, and I would support that.
