### ISSUE TITLE
Parsing logon message fails

### ISSUE THREAD

**Issue by fernandesPabloVexter** [connamara/quickfixn#546]
I'm facing a similar problem as described in issue #465 and i'm already using the latest version (1.8.0).
The error being reported is:
    `QuickFix.MessageParseError: Could not parse message: Error at position (3) while parsing msg (8=FIX.4.49=10835=A34=149=TARGETCOMPID52=20191009-18:29:17.01356=USERNAME95=2196=rtcedro	rtcedro	CHAVE98=0108=10141=Y10=120) ---> System.FormatException: Input string was not in a correct format.`

This is the incoming message, after my initial logon attempt.
Unlike "jmazar" on the related issue, i don't know where to find the ExtractField method to manipulate it and i don't think i need, since the matter he reported have already been fixed.
How can i solve that parse error?

**Comment by gbirchmeier** [comment]
This was fixed in master.  #465 is merged, yes, but it is newer than 1.8.0.  We have not yet released a 1.9.

If you download the most recent source and build, you should have the fix.

**Comment by Kedr91** [comment]
> I'm facing a similar problem as described in issue #465 and i'm already using the latest version (1.8.0).
> The error being reported is:
> `QuickFix.MessageParseError: Could not parse message: Error at position (3) while parsing msg (8=FIX.4.4�9=108�35=A�34=1�49=TARGETCOMPID�52=20191009-18:29:17.013�56=USERNAME�95=21�96=rtcedro rtcedro CHAVE�98=0�108=10�141=Y�10=120�) ---> System.FormatException: Input string was not in a correct format.`
> 
> This is the incoming message, after my initial logon attempt.
> Unlike "jmazar" on the related issue, i don't know where to find the ExtractField method to manipulate it and i don't think i need, since the matter he reported have already been fixed.
> How can i solve that parse error?

Hi there; i have the same issue in Mac OSX Mojave and Linux Elementary; i compliled the source following ypur instructions and installing Ruby, but what i get is a lot of little quickfix.dll; how to get the complete almost 20MB dll file? many thanks.
