### ISSUE TITLE
Please publish a new version to NuGet.org 

### ISSUE THREAD

**Issue by nctxzf** [connamara/quickfixn#563]

**Comment by gbirchmeier** [comment]
This is in our plans as soon as we have some time for it.

But please note: any current NuGet packages that are out there were not created by us and are completely unauthorized.  We have never published a NuGet package.

Also, using a Nuget package means you're not using a build tailored for your specific interface, with typesafe message and field functions.  I generally recommend that all seasoned users users should regenerate the QF/n source off of their own DD and make a custom build.
