### ISSUE TITLE
Sourcelink

### ISSUE THREAD

**Issue by VinceAvery** [connamara/quickfixn#565]
Are there any plans to include source link for the Nuget package?
It makes the debugging experience much smoother

https://github.com/dotnet/sourcelink

**Comment by gbirchmeier** [comment]
The NuGet package is not official.  We did not release it.

We are planning to release a NuGet, when we have time.  See #564 .

We can look into Sourcelink.  First time I'm hearing about it.

**Comment by gbirchmeier** [comment]
I'm very much open to someone prototyping this feature and convincing me why it's great, but it's not something I have time to investigate in the near future, so I'm closing this.
