### ISSUE TITLE
Misleading SSLCheckCertificateRevocation configuration

### ISSUE THREAD

**Issue by Mad-Lynx** [connamara/quickfixn#566]
In the documentation it's stated that:
> Setting the value **SSLValidateCertificates** to N will also set **SSLCheckCertificateRevocation** to N.

But in reality these two does not correlate.
Even if we set the `SSLValidateCertificates` to false, the `SSLCheckCertificateRevocation` will stay true.

So yes, you will not proceed with certificate validation 
https://github.com/connamara/quickfixn/blob/84bbfb09d93ce712e7ff73ac1f57c36338d0bc5f/QuickFIXn/Transport/StreamFactory.cs#L348

But you will still pass true to `AuthenticateAsClient`:
https://github.com/connamara/quickfixn/blob/84bbfb09d93ce712e7ff73ac1f57c36338d0bc5f/QuickFIXn/Transport/StreamFactory.cs#L255

Which could have some knockout effect if building your CRL takes some time.

So we should have the documentation fixed, saying that "they are not related" and `SSLCheckCertificateRevocation` will stay Y.
Or fix the code and obey documentation, so if in fact we don't want validation, we will also do not `checkCertificateRevocation` calling `AuthenticateAsClient`.

**Comment by gbirchmeier** [comment]
Sorry it took so long for me to get to this, but you are totally right.  I'm not a SSL expert, but seems to me like the docs' scenario makes sense, so I will fix the code.

Let me know if you disagree with that approach (you clearly know more about this topic than me).
