### ISSUE TITLE
Server-side certificates BUT no client-side certificates

### ISSUE THREAD

**Issue by aerlian** [connamara/quickfixn#567]
I don't seem to be able to get the following configuration to work:
1. Server certificate is configured
2. Client certificate is NOT configured

This would lead to a secure channel where the client identity is realized only from SenderCompID value sent in the request from client to server.

I see that QuickFix/J (https://www.quickfixj.org/usermanual/2.0.0/usage/configuration.html) has a setting that I believe I am looking for but cannot find in QuickFix/N:
NeedClientAuth=[Y|N]

Please can someone advise whether this configuration is possible in QuickFix/N and if so how should the config be made?

**Comment by mgatny** [comment]
@aerlian Are you looking for `SSLRequireClientCertificate=N`? 

cc @gbirchmeier

**Comment by aerlian** [comment]
Many thanks and apologies for wasting your time on this one...I obviously need to upgrade my reading glasses

**Comment by mgatny** [comment]
@aerlian no problem, happy to assist
