### ISSUE TITLE
Equivalent function for getGroup in DataDictionary in Quickfix/n.

### ISSUE THREAD

**Issue by muralinit** [connamara/quickfixn#569]
Hi Team,

Previously in our project, we were using **quickfix_net.dll** and **quickfix_net_messages.dll** to parse fix messages. Recently we started using **Quickfix/n** code. When we are refactoring our source code I could not able find an equivalent function for **DataDictionary.getGroup()**. I have gone through the readme and your site as well. Since I could not able to find any help I want to get some help from here. Please advise.

Thanks & Regards,
N.Murali Krishna.

**Comment by gbirchmeier** [comment]
Github issues are for bugs, not help requests.  Please see [this page](http://quickfixn.org/help/) or submit a question on StackOverflow (tag it "quickfixn").

You've probably solved it by now, but I just looked it up, so I'll answer it anyway.

See this test:
https://github.com/connamara/quickfixn/blob/master/UnitTests/DataDictionaryTests.cs#L88

You must first use e.g. `dd.Messages["AE"]` to get the `DDMap` of the message, and you can then call `GetGroup(711)` on that to get a `DDGrp` object.
