### ISSUE TITLE
.NetCore3.1 and QuickFIXn problem

### ISSUE THREAD

**Issue by mkoca** [connamara/quickfixn#571]
Hi;

I try to develop a initiator application and I use .NetCore3.1 and QuickFIXn 1.9.0. I downloaded QuickFIXn 1.9.0 source code from GitHub and build it.But my application throwing a  exception on the Win10 machine when trying connect to acceptor. If I run my application on the Win7 machine everyting is runing and connect to acceptor. I use same config file.

Thanks...

My exception:
20200129-08:36:00.698 : Created session
20200129-08:36:00.762 : Connecting to xx.xx.xx.xx on port 17832
20200129-08:36:01.106 : Unexpected exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at QuickFix.Transport.StreamFactory.CreateTunnelThruProxy(String destIP, Int32 destPort)
   at QuickFix.Transport.StreamFactory.CreateClientStream(IPEndPoint endpoint, SocketSettings settings, ILog logger)
   at QuickFix.SocketInitiatorThread.SetupStream()
   at QuickFix.Transport.SocketInitiator.SocketInitiatorThreadStart(Object socketInitiatorThread)
20200129-08:36:31.168 : Connecting to xx.xx.xx.xx on port 17832

Dotnet Info (dotnet --info):
C:\Users\mkoca\Downloads\dotnet_tmp\dotnet-sdk-3.1.100-win-x64>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\mkoca\Downloads\dotnet_tmp\dotnet-sdk-3.1.100-win-x64\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

**Comment by gbirchmeier** [comment]
CreateTunnelThroughProxy is a 40-line function, so it's hard to figure out which var could be null.  Since you've built the lib yourself, could you use the debug binaries and get a stack trace with line numbers?

I very much want to fix this.  QF/n should not be throwing NullReferenceExceptions.

**Comment by mkoca** [comment]
Hi  Grant;
Thanks for quick reply. 

Stac Trace:
20200128-14:34:24.561 : Connecting to xx.xx.xx.xx on port 17832
20200128-14:34:24.562 : Unexpected exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at QuickFix.Transport.StreamFactory.CreateTunnelThruProxy(String destIP, Int32 destPort) in D:\mkoca\fix_bis\quickfixn-master\QuickFIXn\Transport\StreamFactory.cs:line 40
   at QuickFix.Transport.StreamFactory.CreateClientStream(IPEndPoint endpoint, SocketSettings settings, ILog logger) in D:\mkoca\fix_bis\quickfixn-master\QuickFIXn\Transport\StreamFactory.cs:line 73
   at QuickFix.SocketInitiatorThread.SetupStream() in D:\mkoca\fix_bis\quickfixn-master\QuickFIXn\SocketInitiatorThread.cs:line 74
   at QuickFix.Transport.SocketInitiator.SocketInitiatorThreadStart(Object socketInitiatorThread) in D:\mkoca\fix_bis\quickfixn-master\QuickFIXn\Transport\SocketInitiator.cs:line 64

**Comment by gbirchmeier** [comment]
Here's the line:

**Comment by gbirchmeier** [comment]
Thanks, that's very helpful.

Here's the line:  
https://github.com/connamara/quickfixn/blob/master/QuickFIXn/Transport/StreamFactory.cs#L40

I'm guessing that `proxyUri` is null.  I'll try to dig into this later.

If a lot of time passes, please remind me to do this.

**Comment by ceremony** [comment]
Hi - yes I'm a new user to QuickFix /n  - (though not the trading business) - and I received exactly the same exception, same problem running .NET Core 3.1 on Windows 10.

**Comment by mbmurray** [comment]
The only workaround for this is to roll back your version of .net core.  We originally thought that it would work with .net core 3.0 and had some success but found out last week that we needed to roll back to .net core 2.2 to ensure that it would work as expected.

You can find more detail on the issue and the inconsistencies in implementation from this link on github:  https://github.com/dotnet/runtime/issues/30066

**Comment by mkoca** [comment]
Hi @ceremony;

I edited CreateTunnelThruProxy method of StreamFactory class and rebuilded quickfixn project. My changes is below.

	...
	Uri proxyUri = webProxy.GetProxy(destUri);
	//https://github.com/connamara/quickfixn/issues/571
	if (proxyUri == null) {
		return null;
	}
	IPAddress[] proxyEntry = Dns.GetHostAddresses(proxyUri.Host);
	....

**Comment by mcmillab** [comment]
I've had exactly the same problem and ended up with exactly the same solution.
It seems the webProxy.GetProxy doesn't specify null as a return value, but that's what happens in dotnetCore 3.1

**Comment by mcmillab** [comment]
@gbirchmeier - can this be incorporated into the main branch?

**Comment by gbirchmeier** [comment]
@mcmillab & @mkoca - I just merged this to master.  Thanks for finding the relevant dotnet/runtime project issue, that was very helpful.
