### ISSUE TITLE
BUG: Initiator HeartBtInt=0 is an error

### ISSUE THREAD

**Issue by fourpastmidnight** [connamara/quickfixn#596]
QuickFIX/n throws an exception when an initiator's `HeartBtInt` configuration is set to `0`. However, according to the [documentation for the Heartbeat message](http://fixwiki.org/fixwiki/Heartbeat), when the `HeartBtInt` field of the Logon message is `0`, then no `Heartbeat` messages are to be generated. Therefore, `0` is a valid value for `HeartBtInt`.

**Comment by gbirchmeier** [comment]
thanks, will look into it

**Comment by fourpastmidnight** [comment]
I should note that setting a value of `0` for the Acceptor in the configuration file does **not** cause an exception.

**Comment by gbirchmeier** [comment]
That makes sense; it's only used for Initiator.  Acceptor completely ignores it.

**Comment by gbirchmeier** [comment]
So weird-- I fixed the settings ctor to allow 0, and now the initiator doesn't even send a logon.

This is gonna be a fun one.

**Comment by gbirchmeier** [comment]
Confirmed, per spec (this comes from FIX44 vol 2):

> If HeartBtInt is set to zero then no regular heartbeat messages will be generated. Note that a test request message can still be sent independent of the value of the HeartBtInt, which will force a Heartbeat message.

**Comment by gbirchmeier** [comment]
Fixed!
