### ISSUE TITLE
Repeating group not totally send in FIX message with 43=Y Possible duplicate

### ISSUE THREAD

**Issue by WassFIX** [connamara/quickfixn#599]
when resending fix message with 43=Y, repeating group are not all indicated in the message. 
Only one group is present

**Comment by gbirchmeier** [comment]
Pretty sure this is fixed in 1.9.  (If you are using a nuget package, know that it is old and unofficial and not released by us.)

Regardless, this issue submission is pretty worthless.  If you think you found a real bug on the latest version, please show your config and a message log.
