### ISSUE TITLE
Runtime Error netstandard version 2.0

### ISSUE THREAD

**Issue by WassFIX** [connamara/quickfixn#600]
Hey,

Using 4.5.2 Net Framework, i have a run time error on quickFIXN v1.9:
Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies

Thanks,

**Comment by michaelwilner** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support Minimum .net framework version required is 4.6.1
