### ISSUE TITLE
NuGet Install of QuickFixn Failure

### ISSUE THREAD

**Issue by Ringbretson** [connamara/quickfixn#624]
I'm fairly new to QuickFix and I developed an application using a very old version of QuickFix what was written by a 3'rd party.
I'm trying to rewrite the application using the latest version of QuickFix for C# and I'm getting the following error when I try installing the QuickFIXn.Core package from Nuget.  My guess is that the install package uses a framework prior to V4.6.1, but I've tried V4.5 and V4.4.  Any Idea what I'm doing wrong or what framework I need to use?

Could not install package 'QuickFIXn.Core 1.10.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

Could not install package 'QuickFIXn.FIX4.4 1.10.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by gbirchmeier** [comment]
The latest QF/n is targeting .NET Core 2.0.

This page has more information on that:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Framework 4.6.1 is pretty old.  If you're upgrading QF/n, you might as well upgrade your .NET as well!

**Comment by gbirchmeier** [comment]
(Correction: it supports .NET *Standard* 2.0.  I erroneously said "Core" above, but have corrected it.)

**Comment by Ringbretson** [comment]
Same result with 4.7.2 framework.  

I attached a screen shot of installed DLL’s.  Should it work with these versions?

 

 

 


Severity

Code

Description

Project

File

Line

Suppression State


Error

 

Could not install package 'QuickFIXn.Core 1.10.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

 

 

0

**Comment by gbirchmeier** [comment]
Can't see your screenshot, but I'm not sure if I need to.  (Maybe next time try uploading via the github issue page instead of emails.)

I am using Visual Studio Community 2019 (v16.4.5), if that matters.

I just checked my demo app which was created as a .NET Core console app, and I'm able to target both .NET Core 2.0 and 3.1.  (This app was created under VS v15, though obviously I'm using v16 today on it.)

I just now created a new .NET Framework console app, and I was able to install QF/n and compile with no problem.  See attached screenshot.

![Screen Shot 2020-06-30 at 13 45 45](https://user-images.githubusercontent.com/237288/86164931-2da96580-bad8-11ea-8658-17b4c7e5180a.png)

**Comment by Ringbretson** [comment]
Microsoft.NETCore.Platforms V3.1.1
NETStandard.Library V2.0.3

**Comment by gbirchmeier** [comment]
Have you tried creating a new project and pulling QF/n into it?

I'm guessing there's an odd legacy setting in your old app that's causing the issue.  Might be helpful to compare the csproj files of your problem application with new "clean" csproj files of a new QF/n app.

**Comment by gbirchmeier** [comment]
Closing due to lack of replies.
