### ISSUE TITLE
QuickFix Dictionary .ctor overload doesn't capitalize keys

### ISSUE THREAD

**Issue by fourpastmidnight** [connamara/quickfixn#639]
When using the `.ctor` overload for `QuickFix.Dictionary(string name, Dictionary<string, string> data)`, this overload does not capitalize the key names in the `data` dictionary, causing a runtime exception when `GetString` is called. 

Line 59 could be something like:

```csharp
data_ = data.Select(kvp => new {k = kvp.Key.ToUpperInvariant(), v = kvp.Value}).ToDictionary(x => x.k, x => x.v);
```

**Comment by gbirchmeier** [comment]
You're technically not wrong about that line, but as far as I can tell, it's impossible to set a key that isn't all-uppercase.  All setter functions perform ToUpper() on the key before saving internally.  It's not possible to construct a `data` that can trigger this error.

Now that my head's in it, I'll update the line anyway (and also do some other cleanup), but I'm pretty sure it's a non-issue.

**Comment by gbirchmeier** [comment]
No, I'm wrong!

The `data` parameter is a generic Dictionary, not a QF Dictionary, and it /can/ have lower-case keys!

Argh, I'm going to rename this class to SettingsDictionary.  This isn't the first time I've gotten a little confused.
