### ISSUE TITLE
SocketClosed by Listener exception when using samples in high speed loop

### ISSUE THREAD

**Issue by undecided2013** [connamara/quickfixn#651]
I converted the TradeClient sample to create random orders in a loop in order to test throughput. I have a Thread.Sleep(ms) in the loop. If the sleep is less than 20ms, the Acceptor Sample does not respond and the tradeclient crashes with a socket closed exception. If I set the sleep to 20ms or higher, the Acceptor and TradeClient work harmoniously together.

Logs have this in them

20200818-13:49:25.641 : Session FIX.4.4:SIMPLE->CLIENT1 already disconnected: Resetting...
20200818-13:49:25.647 : Session reset: New session
20200818-13:49:25.647 : Created session
20200818-13:49:39.559 : FIX.4.4:SIMPLE->CLIENT1 Socket Reader 59817589 accepting session FIX.4.4:SIMPLE->CLIENT1 from 127.0.0.1:58496
20200818-13:49:39.559 : FIX.4.4:SIMPLE->CLIENT1 Acceptor heartbeat set to 0 seconds
20200818-13:49:39.566 : Session FIX.4.4:SIMPLE->CLIENT1 disconnecting: Received msg type 'D' when not logged on
20200818-13:49:39.571 : Session reset: ResetOnDisconnect

Looks like some kind of race condition.

**Comment by gbirchmeier** [comment]
I'm not surprised that QF/n has perf issues under extreme throughput.

If someone presents a perf-test rig and proposes solutions, I'm here for that.  But users aren't reporting perf problems in practice, so I'm not going to kick off my own investigation based on this issue.
