### ISSUE TITLE
NullReferenceException in QuickFIXn/AbstractInitiator.cs at line 237, IsLoggedOn property

### ISSUE THREAD

**Issue by akpwhg** [connamara/quickfixn#662]
foreach (SessionID sessionID in connected_)
                    {
                        if (Session.LookupSession(sessionID).IsLoggedOn)
                            return true;
                    }

Above code will throw NullReferenceException when Session.LookupSession(sessionID) returns null.

Had this occur couple of times while reconnecting to an unreachable server, have not been able to reproduce in a test scenario.

Possible fix:

                    foreach (SessionID sessionID in connected_)
                    {
                        Session session = Session.LookupSession(sessionID);
                        return session != null && session.IsLoggedOn;
                    }

**Comment by gbirchmeier** [comment]
I made the fix.  Thanks!
