### ISSUE TITLE
TimeZoneNotFoundException when running in Linux

### ISSUE THREAD

**Issue by israelolcha** [connamara/quickfixn#664]
Setting key 'TimeZone' in session dictionary raises an exception when running dotnet core 3.1 in linux.
This is because the TimeZoneInfo is not present under linux. 
You should use  TimeZoneConverter package that works in both windows and linux

**Comment by gbirchmeier** [comment]
Please tell me more about the error you see.  We have a few UTs that directly call TimeZoneInfo and it appears to work fine when I build on Mac.

Going to close this for not-enough-info.  If you respond, I'll reopen it.
