### ISSUE TITLE
Char Encoding Process Chinese Characters?

### ISSUE THREAD

**Issue by harleybl** [connamara/quickfixn#670]
I have a FIX connection with a broker in Singapore that occasionally sends me messages with Chinese characters in them. 
When I receive these messages my client fails to process them and logs out. 
The broker sends the message again when I reconnect and my client gets into a loop of disconnecting and reconnecting.
To regain connectivity I have to stop my client, manually increment the sequence number, and restart the client to get past the bad message.

Here is an example of the message that can't be processed (with sensitive info changed):
20210120-15:13:06.305 : 8=FIX.4.49=27335=834=15743=Y49=BROKR52=20210120-15:07:06.12156=OUR_COMPID122=20210120-12:52:35.7971=999999996=011= 14=017=031=032=037=538=40039=840=R44=-99.99954=155=SYMBL58=����״̬��鲻�Ϸ�!150=8151=400167=FUT207=EXC5001=25006=05007=05012=020921985111=110=156

I think it is failing on the text field (58).

The body length they are sending is 273, but QuickFix/N is calculating it to be 288.

Here is the stack trace:
QuickFix.InvalidMessage: Invalid message: Expected BodyLength=288, Received BodyLength=273
   at QuickFix.Session.Next(MessageBuilder msgBuilder)
   at QuickFix.Session.NextMessage(String msgStr)
   at QuickFix.Session.Next(String msgStr)
   at QuickFix.SocketInitiatorThread.ProcessStream()
   at QuickFix.SocketInitiatorThread.Read()

I noticed in the code that the default character encoding iso-8859-1.
Should that be able to process this message? 
Is there something I can do in the configuration to either help stay out of the connect/disconnect loop.

**Comment by gbirchmeier** [comment]
Github is not for help requests.  Please see http://quickfixn.org/help/

Also, if you are using a NuGet package, make sure you are using [an official release](http://quickfixn.org/download/) and not one of the out-of-date builds published by other people.
