### ISSUE TITLE
Cannot select a different Proxy 

### ISSUE THREAD

**Issue by njimenez** [connamara/quickfixn#677]
We are trying to bypass the default proxy and use our own proxy, but the call in StreamFactory is making use of the 
wrong (I think) call. 

Instead of calling WebRequest.GetSystemWebProxy, it should be using WebRequest.DefaultWebProxy, this way we could override it in the config file. Or allow in the settings to specify a Proxy Host and port.

-    GetSystemWebProxy Returns a proxy configured with the Internet Explorer settings of the currently impersonated user.

-    The DefaultWebProxy property reads proxy settings from the app.config file. If there is no config file, the current user's Internet Explorer (IE) proxy settings are used.

**Comment by gbirchmeier** [comment]
Are you affiliated with "vijay" who sent an email to our web form?

I admit that this is not a subject area I'm well-versed in.  This particular feature came from a submission.

But it sounds like you know what you're doing.  Would you be interested in attempting to make that code change, ensuring it passes tests (updating any as necessary), and submitting a PR?

**Comment by njimenez** [comment]
Unfortunately I am bounded by endless NDA and NCA that I would be very scare making any type of PR. 

Sorry.

When my situation changes I will try and help you out.

Nelson Jimenez

**Comment by gbirchmeier** [comment]
addressed by #697
