### ISSUE TITLE
FIX message contains bad character, how can we skip it

### ISSUE THREAD

**Issue by DHirani** [connamara/quickfixn#683]
We have certain brokers sending us a FIX message where the tag 58 value contains invalid characters that causes the FIX engine to stop with "Invalid message: Expected ..." 

Session FIX.4.4:TEST->CLIENT disconnecting: QuickFix.InvalidMessage: Invalid message: Expected BodyLength=797, Received BodyLength=795
   at QuickFix.Session.Next(MessageBuilder msgBuilder)
   at QuickFix.SocketInitiatorThread.ProcessStream()
   at QuickFix.SocketInitiatorThread.Read()

**Workaround**
1. Stop FIX engine and jump the sequence number by one.

Is it possible to extend QuickFixN so it delivers the payload as bad message then jumps to the next message?

**Comment by stbrd** [comment]
Running into the same exact issue but with a different tag (65). Would like to reject the invalid message and move on to the next, but QuickFixN stops and cannot move to subsequent messages without manual intervention.

**Comment by gbirchmeier** [comment]
Yes, if you are not using QF/n 1.10, please upgrade and try again.
