### ISSUE TITLE
No way to turn off logging in ClientHandlerThread?

### ISSUE THREAD

**Issue by efpies** [connamara/quickfixn#684]
Today we've experienced an issue regarding inability to create new files on server. Turned out, the `log` directory was filled with literal millions of files (half of which were empty). And the code on server was running for just 3 weeks.

And the reason for that is this piece of code:

```
string debugLogFilePath = "log";
if (settingsDict.Has(SessionSettings.DEBUG_FILE_LOG_PATH))
    debugLogFilePath = settingsDict.GetString(SessionSettings.DEBUG_FILE_LOG_PATH);
else if (settingsDict.Has(SessionSettings.FILE_LOG_PATH))
    debugLogFilePath = settingsDict.GetString(SessionSettings.FILE_LOG_PATH);

// FIXME - do something more flexible than hardcoding a filelog
log_ = new FileLog(debugLogFilePath, new SessionID(
        "ClientHandlerThread", clientId.ToString(), "Debug-" + Guid.NewGuid().ToString()));
```

So it seems, we'll always write debug logs, even in production. There should be a way to turn it off without commenting the code.

**Comment by gbirchmeier** [comment]
This was addressed in #830, and included in release 1.12.0
