### ISSUE TITLE
DateTimeConverter encodign correct 

### ISSUE THREAD

**Issue by PaxHumana** [connamara/quickfixn#686]
Calls to string.Format in the DateTimeConverter does not make use of DATE_TIME_CULTURE_INFO, the decoder does use is. Result is this will only work if encoding party uses the expected cultureinfo

See ex  public static string Convert(System.DateTime dt, TimeStampPrecision precision ) line 242, should be:

public static string Convert(System.DateTime dt, TimeStampPrecision precision )
        {
            if (precision == TimeStampPrecision.Nanosecond)
            {
                return string.Format(DATE_TIME_CULTURE_INFO, DATE_TIME_FORMAT_WITH_NANOSECONDS, dt, dt.SubsecondAsNanoseconds());
            }
            else
            {
                var format = DATE_TIME_PRECISION_TO_FORMAT[precision];
                return string.Format(DATE_TIME_CULTURE_INFO, format, dt);
            }
        }

**Comment by PaxHumana** [comment]
Same issue in the UtcDateTimeSerializer, ToString does not use cultureinfo.InvariantCulture

**Comment by esamdal-aurora** [comment]
This problem can be reproduced by setting the time separator in the current thread's culture to something else than ":".
E.g.

`
var culture = CultureInfo.CreateSpecificCulture(Thread.CurrentThread.CurrentCulture.Name);
DateTimeFormatInfo dtfi = culture.DateTimeFormat;
dtfi.TimeSeparator = ".";
Thread.CurrentThread.CurrentCulture = culture;

var field = new DateTimeField(9999, DateTime.UtcNow);
Console.WriteLine("The time is invalid here:" + field.ToString());
`

**Comment by gbirchmeier** [comment]
Fixed by #764 (and may yet be improved by #765)
