### ISSUE TITLE
Using Message.ToXML() - field names are missing

### ISSUE THREAD

**Issue by JP1852** [connamara/quickfixn#690]
Hello Team,

I'm trying to use the Message.toXML() function, but realise that field names are always missing.
I believe the dataDictionary_ protected variable is never set in the different constructors...

Thanks

**Comment by gbirchmeier** [comment]
This is a very little-used feature.  I'm not even convinced we should keep it in the project.

If you think you know a fix, I invite you to give it a try.  I don't think anyone else is going to jump in on this anytime soon.

Thanks (and sorry?).

**Comment by JP1852** [comment]
Thank you very much for your reply and agree, not sure it should be fix.
Let's close the issue then, and I'ill reopen if I get time to dive into it and fix.
Thanks again :-)
