### ISSUE TITLE
Message parsing not working (Linux - Ubuntu)

### ISSUE THREAD

**Issue by fernandozago** [connamara/quickfixn#693]
Hello guys,

I`m trying to make a working sample in a Linux Machine (with ubuntu).
But when the method FromAdmin(Message msg... is invoked, on Windows it parses to a right message type. Eg.

switch (msg)
case QuickFix.FIX44.Reject reject: (On windows it works fine)

On linux it cannot pase to the correct base type.

Any thoughs ?

**Comment by gbirchmeier** [comment]
Please ask on the mailing list or StackOverflow.  Thanks.
http://quickfixn.org/help

When you ask, please note which build or nuget packages you are using.
