### ISSUE TITLE
Bypass credentials to a proxy

### ISSUE THREAD

**Issue by mcjacek** [connamara/quickfixn#695]
I am trying to establish a connection with quickfix/n but I am behind the company firewall. So I need to connect over a proxy to the acceptor. According to the [documentation ](https://quickfixj.org/usermanual/2.3.0/usage/configuration.html)of quickfix/j it is possible via JAVA, however in the [documentation ](http://quickfixn.org/tutorial/configuration.html)of quickfix/n there is no information about possibility of connecting to the acceptor over a proxy via quickfix/n, that is secured with a password.
I've found this method:
`private static Socket CreateTunnelThruProxy(string destIP, int destPort)`
and it bypassing proxy details, but 2 points could be considered:
- current implementation does not support username/password to the proxy (for example I need to authenticate with credentials for my company proxy)
- it is not possible to bypass proxy details via config (in case I want to use non-standard proxy) (WebRequest.DefaultWebProxy instead of WebRequest.GetSystemWebProxy()]

**Comment by ABSJ415** [comment]
We are experiencing something similar - we need to bypass the proxy usage, so the connection would be made directly. 
Therefore, turning off proxy resolution, even if it is setup and available.

This is something that we need, so I'm willing to do the PR change for quickfixn - adding a setting for turning off the proxy resolution.

I was looking also into replicating the proxy configuration so it is similar as for quickfix/j, but from my perspective without using the help of socks5, it would be quite complicated to achieve... 

Does that sound reasonable and would you accept such PR?

**Comment by gbirchmeier** [comment]
@ABSJ415 Yeah, we'd certainly be willing to look at a PR

**Comment by ABSJ415** [comment]
> @ABSJ415 Yeah, we'd certainly be willing to consider your PR

@gbirchmeier Please if you could look at and approve #697

**Comment by gbirchmeier** [comment]
addressed by #697
