### ISSUE TITLE
Library does not support .NET 5.0 on Alpine Linux

### ISSUE THREAD

**Issue by Svisstack** [connamara/quickfixn#696]
We have perfectly working code on 
  `<TargetFramework>netcoreapp3.1</TargetFramework>`
that is compiled using 
  `FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build`
and run using 
  `FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS base`
in docker container.

But when we upgrade the framework to
  `<TargetFramework>net5.0</TargetFramework>`
compile using
  `FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build`
and run using 
  `FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base`

Then there is no exception visible but the initiator does not start the session.

When running .NET 5.0 version of the Windows, everything works fine.

**Comment by gbirchmeier** [comment]
I have a branch where I've updated the build and demo apps to .NET 6.0, and everything appears to be working.

Since 5.0 is now EOL, I'm going to close this issue.  Please reply if you think there is still an issue here.

**Comment by Svisstack** [comment]
@gbirchmeier Good to hear that however I do not see any branches in the repository; and also it seems that it was not merged to the master; latest tag is from the Jun 25, 2020 (v1.10.0). Can you point me to where you pushed fixes for the .net6.0?

**Comment by gbirchmeier** [comment]
See reply in #713
