### ISSUE TITLE
Keep Loging On

### ISSUE THREAD

**Issue by FadiNeh** [connamara/quickfixn#699]
Initiator Keep logging on and the acceptor is returning a type 'j' message to the initiator, and the initiator keep disconnecting and connecting. Nothing complicated is implemented, just trying to logon a initiator to an acceptor.

**Comment by gbirchmeier** [comment]
This is normal behavior when there is something wrong in the logon message.  The rejection reason should be in the "j" message.

If you want more help, please join the [mailing list](http://quickfixn.org/help) or ask on StackOverflow (tag it "quickfixn").  Github issues are for bugs, not help requests.
