### ISSUE TITLE
QUICKFIX 4.4 ON UBUNTU SERVER {System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.  ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.  ---> Interop+Crypto+OpenSslCryptographicException: error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type    --- End of inner exception stack trace ---    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)    --- End of inner exception stack trace ---

### ISSUE THREAD

**Issue by freefred81** [connamara/quickfixn#700]
Hi I'm tryng to running my app build on DOTNET CORE3.1 (and not 5) which run with no problem on a windows server in a Linux ubuntu server.

It give me this log:

> 
> {System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
>  ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
>  ---> Interop+Crypto+OpenSslCryptographicException: error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
>    --- End of inner exception stack trace ---
>    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
>    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
>    --- End of inner exception stack trace ---
>    at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
>    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
>    at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
>    at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
>    at QuickFix.Transport.StreamFactory.SSLStreamFactory.CreateClientStreamAndAuthenticate(Stream innerStream)
>    at QuickFix.Transport.StreamFactory.CreateClientStream(IPEndPoint endpoint, SocketSettings settings, ILog logger)
>    at QuickFix.OnlyAuth.Frameworks.Utils.MySocketInitiatorThread.SetupStream() in C:\_massi\NTHTBRAINSTORM\lib\QuickFix.OnlyAuth.Frameworks\Utils\MySocketInitiatorThread.cs:line 77
>    at QuickFix.OnlyAuth.Frameworks.Utils.MySocketInitiatorThread.Connect() in C:\_massi\NTHTBRAINSTORM\lib\QuickFix.OnlyAuth.Frameworks\Utils\MySocketInitiatorThread.cs:line 68
>    at QuickFix.OnlyAuth.Frameworks.Utils.MySocketInitiator.SocketInitiatorThreadStart(Object socketInitiatorThread) in C:\_massi\NTHTBRAINSTORM\lib\QuickFix.OnlyAuth.Frameworks\Utils\MyInitiator.cs:line 66}
>    
>    
>    
>    SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
> 

 

I try to change the certificate (pfx) that i'm using but if i change format it give me error on the certificate type (for example with .p12 or other format)

Any idea on what could happen? 

Should it work on a linux ubuntu server with quickfix 4.4 lib?

Thnx!

Here is my conf:

 ```
var configuration = new System.IO.StringReader(new System.Text.StringBuilder()
                    .AppendLine("[DEFAULT]")
                    .AppendLine("ConnectionType=initiator")
                    .AppendLine("BeginString=FIX.4.4")
                    .AppendLine("ResetOnLogon=Y")
                    .AppendLine("ResetOnDisconnect=Y")
                    .AppendLine("SocketConnectHost=" + gainConfiguration.Host)
                    .AppendLine("LogoutTimeout=5")
                    .AppendLine("SocketConnectPort=" + gainConfiguration.Port)
                    .AppendLine("DataDictionary=./spec/fix/FIX44.xml")
                    .AppendLine("UseDataDictionary=N")
                    .AppendLine("StartTime=00:00:00")
                    .AppendLine("EndTime=00:00:00")
                    .AppendLine("Verbose=Y")
                    .AppendLine("HeartBtInt=30")
                    .AppendLine("LogonTimeout=30")

                    .AppendLine("SSLEnable=" + gainConfiguration.SSLEnable)
                    .AppendLine("SSLCertificate=./assets/certificate/mycert.pfx" )
                    .AppendLine("SSLCertificatePassword=MyPasswd")
                    .AppendLine("SSLValidateCertificates=N")
             

                    .AppendLine("Password=" + gainConfiguration.Password)
                    .AppendLine("FileStorePath=store")
                    .AppendLine("FileLogPath=log")
                    .AppendLine("ReconnectInterval=2")
                    .AppendLine("SocketReuseAddress=Y")
                    .AppendLine("SocketAcceptPort=5005")
                    .AppendLine("Username=" + gainConfiguration.UUID)
                    .AppendLine("[SESSION]")
                    .AppendLine("BeginString=FIX.4.4")
                    .AppendLine("SenderCompID=" + gainConfiguration.SenderID)
                   
                    .AppendLine("TargetCompID=" + gainConfiguration.TargetID)

                    .ToString());
```

 
 

(I'm sure about password and user etc etc .. the same code works perfect on my windows server)

**Comment by gbirchmeier** [comment]
I'm sorry I can't help much with this, SSL Authentication is not one of my areas of expertise.

Try asking on the mailing list?

quickfixn.org/help
