### ISSUE TITLE
Is there a plan to add the key TimestampPrecision?

### ISSUE THREAD

**Issue by lijielile** [connamara/quickfixn#702]
I am trying to send timestamps with nanoseconds precisions but currently it is not supported in quickfix/n. I found in quickfix that they have this key called TimestampPrecision but it is not available in quickfix/n. Is it possible to add this key to quickfix/n?

**Comment by dckorben** [comment]
I currently handle stamps with nanoseconds, however, .NET only has 100ns precision so if you need full precision, you will need a different solution.

**Comment by gbirchmeier** [comment]
We did nano precision in #459, but like @dckorben says, it's only 100ns precision.
