### ISSUE TITLE
Unknown error while processing the certificate

### ISSUE THREAD

**Issue by grantweii** [connamara/quickfixn#703]
Hi, I'm implementing self-signed TLS (testing purposes, prod will not be self signed), however, I am getting an error that is not particularly useful. I'm hosting server and client myself (again, for testing purposes), hence the address I am using is localhost. Server has serverAuth extension, client has no extensions. CA has been added to trusted store. Am I missing something?

`
System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: An unknown error occurred while processing the certificate
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at QuickFix.SocketInitiatorThread.ReadSome(Byte[] buffer, Int32 timeoutMilliseconds)
   at QuickFix.SocketInitiatorThread.Read()
`

My acceptor SSL config is as follows:
```
SSLEnable=Y
SSLProtocols=Tls12
SSLValidateCertificates=Y
SSLCheckCertificateRevocation=N
SSLCertificate=server.pfx
SSLCACertificate=ca.cer
SSLRequireClientCertificate=Y
```

My initiator SSL config is as follows:
```
SSLEnable=Y
SSLProtocols=Tls12
SSLValidateCertificates=Y
SSLCheckCertificateRevocation=N
SSLServerName=localhost
SSLCertificate=client.pfx
SSLCACertificate=ca.cer
```

**Comment by gbirchmeier** [comment]
I recommend you ask the mailing list ([see here](http://quickfixn.org/help/)) and maybe also StackOverflow.  This feature was an outside submission, and the people who know it are probably not watching Github issues.

I'm going to close this because it is more of a help request than a bug.
