### ISSUE TITLE
Does it support CipherSuites?

### ISSUE THREAD

**Issue by nikitaso** [connamara/quickfixn#706]
Was trying to add CipherSuites or SSLCipherSuites in config but doesn't look like its working. Checked source code and don't see any reference for it. Some help appreciated.

**Comment by gbirchmeier** [comment]
I have no idea what CipherSuites is, so I strongly believe that we don't support it.

**Comment by nikitaso** [comment]
Thanks for quick reply! I assume java version is very different from .net, you can find more info here https://www.quickfixj.org/usermanual/2.3.0/usage/configuration.html and https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html

perhaps some alternative I can implement?

**Comment by gbirchmeier** [comment]
This (SSL in general) is not a topic that I know well.  Whatever support we have came from a code submission.  I'd suggest asking on the mailing list: http://quickfixn.org/help/
