### ISSUE TITLE
[Bug] Direct 0.0.0.0 address binding

### ISSUE THREAD

**Issue by bohdanstefaniuk** [connamara/quickfixn#711]
When we setup 0.0.0.0 explicitly as socket accept host we get an exception:
`IPv4 address 0.0.0.0 are unspecified that cannot be used as a target address`.

As a user I want to directly setup 0.0.0.0 inside my Docker container and use 127.0.0.1 on my local machine.

I looked into code and found where this exception throws. If you accept pull request I can fix this behaviour and create PR :)

**Comment by gbirchmeier** [comment]
resolved by PR #712
