### ISSUE TITLE
just cannot build successfully for a custom message xml file.

### ISSUE THREAD

**Issue by AliceZHLee** [connamara/quickfixn#725]
I want to build a custom message xml file for FIX4.4.

I just follow the guide on your github: i donwload the repository and paste my customized FIX44.xml into the ./quickfixn/spec/fix/FIX44.xml and open the QuickFIXn solution and run the 
gem install nokogiri
ruby generator\generate.rb
inside the package manager console. and run build.bat inside the folder.
 But it always tells me that "The type or namespace name 'ApplVerID' does not exist in the namespace 'QuickFix.Fields' (are you missing an assembly reference?)	QuickFix (netstandard2.0)" and "The type or namespace name 'MsgType' does not exist in the namespace 'QuickFix.Fields' (are you missing an assembly reference?)". Can anyone guide and help me to overcome this?

In my opinion, if build correctly, then i can get the quickfix44.dll and use it in my project but because of the above issue, the dll cannot be generated.

**Comment by gbirchmeier** [comment]
This is strange.  Even if ApplVerID isn't in your FIX44 dictionary, it should be in the FIX5+ dictionaries.  You still have those FIX5 dictionaries in spec/fix/, don't you?

**Comment by gbirchmeier** [comment]
Closing because lack of response
