### ISSUE TITLE
FIX 5.0 doesn't crack login, logout, heartbeat

### ISSUE THREAD

**Issue by prozerran** [connamara/quickfixn#731]
Hello, I'm currently using FIX TradeClient connected to a FIX server version FIX50 through FIXT.1.1
However when i implement FromAdmin as...

```
        public void FromAdmin(Message message, SessionID sessionID)
        {
            try
            {
                Crack(message, sessionID);
            }
            catch (Exception ex)
            {
                Log.Error($"{ex.Message}");
            }
        }
```

It cannot and does not able to "crack" the message for login, logout, and heartbeat. 
I especially need for the heartbeat part so therefore I cannot implement the method.....

```
        public void OnMessage(QuickFix.FIX50.HeartBeat m, SessionID s)
        {
                 // do my stuff here.....
        }
```

Why is it i cannot implement the OnMessage functions for heartbeat, login, logout.
It doesnt have it. I remember for FIX42 i was able to do it such as ....

```
        public void OnMessage(QuickFix.FIX42.Login m, SessionID s)
        {
            Log.Information("FIX Logon.");
        }
```

Were these intentionally missing, or is there a way for me to capture OnMessage for heartbeat
in FIX5.0

The biggest problem here is that on calling Crack, it throws an exception because it doesnt know how to handle
QuickFix.FIX50.HeartBeat, QuickFix.FIX50.Login, QuickFix.FIX50.Logout

Thanks,
Tim

**Comment by mgatny** [comment]
refs #732
