### ISSUE TITLE
Can you to do Message.FromString as virtual?

### ISSUE THREAD

**Issue by P9avel** [connamara/quickfixn#733]
Hi, for my tasks need to override this method. I am need in Message class description

public virtual void FromString(string msgstr, bool validate,
            DataDictionary.DataDictionary sessionDD, DataDictionary.DataDictionary appDD, IMessageFactory msgFactory,
            bool ignoreBody)

Can you to do this in sources?

**Comment by gbirchmeier** [comment]
I think we need more information on this situation before we decide to make such a code change.

I'm closing this.  But please comment further if you'd like to make a case.
