### ISSUE TITLE
LegSettlType defined as char but should be string (Tag 587)

### ISSUE THREAD

**Issue by raymondjstone** [connamara/quickfixn#735]
Bloomberg (and presumably others) have this field as a string so that values like M1 can be used however it seems to be defined as a char in quickfix/N

**Comment by raymondjstone** [comment]
On further investigation while Bloomberg documentation says string the fix 4.4 standard says char and all the way to to 5.0 Sp2 it's a char but in Fix.Latest it is a string.

**Comment by gbirchmeier** [comment]
It's trivial for any user to edit their DD to make it a string if their counterparty needs that.  I'm going to close this.
