### ISSUE TITLE
FIX acceptor creates a lot of empty files

### ISSUE THREAD

**Issue by nmandzyk** [connamara/quickfixn#736]
When the FIX application is configured as an acceptor with SSL.  FIX TCP port is exposed to the Internet and health probs, and a ton of empty log files are created after the SSL handshake fails, as in the image below:

![image](https://user-images.githubusercontent.com/39336135/182260889-bba2e823-a117-4ee4-9637-af8bb9781976.png)

**Comment by gbirchmeier** [comment]
This was addressed by the new NonSessionLog feature, see #830.

This was in release 1.12.0
