### ISSUE TITLE
How to send a fix recovery U2 request using this library?

### ISSUE THREAD

**Issue by asadsahi** [connamara/quickfixn#737]
As documented here:

https://library.tradingtechnologies.com/tt-fix/recovery/Msg_RecoveryRequest_U2.html

I am not able to find any message type that this library supports, however, in FIX44.xml there is this message type:

```
<message name="OutOfBandRecoveryRequest" msgcat="app" msgtype="U2">
			<field name="StartDate" required="Y" />
			<field name="EndDate" required="Y" />
			<field name="SecurityExchange" required="N" />
			<field name="ExDestination" required="N" />
</message>
```

How can I build a request to send a recovery request using quickfixn client?

**Comment by gbirchmeier** [comment]
Not a bug.  Please see [this page](https://new.quickfixn.org/n/support/) for the proper avenues to ask for help.

**Comment by asadsahi** [comment]
@gbirchmeier I understand this isn't a but, but I wasn't able to find any pointers on the quickfixn documentation or an existing issue/question someone else has raised before. Raised a stackoverflow question anyway.

https://stackoverflow.com/questions/73321677/how-to-send-a-fix-recovery-request-u2-using-this-quickfixn

Any pointer would help.

Thanks
