### ISSUE TITLE
Support unsigned 64-bit integers for sequence numbers

### ISSUE THREAD

**Issue by JohnGreenan** [connamara/quickfixn#760]
Per https://www.fixtrading.org/groups/continuousmkts/
Sequence number resets are a bore.

The implementation proposed is to use an unsigned 64 bit integer for a sequence number.

Using 1 billion sequence numbers per second, that will last for 584 years until they run out.

So we can leave the problem to our great, great, great (more) grandchildren to solve!
![delete_me](https://user-images.githubusercontent.com/8924979/224880260-87b198cb-649d-4d11-a000-2d2a11c53b9b.jpg)

Would be good to include a set of test cases so that testing will be quick.
[Continuous Markets WG- 24x7 FIX Best Practise Working Draft_v0.015.docx](https://github.com/connamara/quickfixn/files/10963688/Continuous.Markets.WG-.24x7.FIX.Best.Practise.Working.Draft_v0.015.docx)

**Comment by JohnGreenan** [comment]
See also:
https://github.com/da4089/simplefix/issues/50
https://github.com/quickfix-j/quickfixj/issues/621
https://github.com/quickfix/quickfix/issues/419
https://github.com/connamara/quickfixn/issues/760

**Comment by forexweb3trading** [comment]
> Per https://www.fixtrading.org/groups/continuousmkts/ Sequence number resets are a bore.
> 
> The implementation proposed is to use an unsigned 64 bit integer for a sequence number.
> 
> Using 1 billion sequence numbers per second, that will last for 584 years until they run out.
> 
> So we can leave the problem to our great, great, great (more) grandchildren to solve! ![delete_me](https://user-images.githubusercontent.com/8924979/224880260-87b198cb-649d-4d11-a000-2d2a11c53b9b.jpg)
> 
> Would be good to include a set of test cases so that testing will be quick. [Continuous Markets WG- 24x7 FIX Best Practise Working Draft_v0.015.docx](https://github.com/connamara/quickfixn/files/10963688/Continuous.Markets.WG-.24x7.FIX.Best.Practise.Working.Draft_v0.015.docx)



> Per https://www.fixtrading.org/groups/continuousmkts/ Sequence number resets are a bore.
> 
> The implementation proposed is to use an unsigned 64 bit integer for a sequence number.
> 
> Using 1 billion sequence numbers per second, that will last for 584 years until they run out.
> 
> So we can leave the problem to our great, great, great (more) grandchildren to solve! ![delete_me](https://user-images.githubusercontent.com/8924979/224880260-87b198cb-649d-4d11-a000-2d2a11c53b9b.jpg)
> 
> Would be good to include a set of test cases so that testing will be quick. [Continuous Markets WG- 24x7 FIX Best Practise Working Draft_v0.015.docx](https://github.com/connamara/quickfixn/files/10963688/Continuous.Markets.WG-.24x7.FIX.Best.Practise.Working.Draft_v0.015.docx)

Which institution is responsible for maintaining sequence numbers of such magnitude and duration?

Are you anticipating the acceptor to retain all the records for several years?

I believe this approach is better suited for the retail sector.

Given that we have already generated numerous carbon footprints, why should we continue to create problems for our grandchildren to solve?
