### ISSUE TITLE
Sellside simulator 

### ISSUE THREAD

**Issue by Harryani** [connamara/quickfixn#777]
We have been using this simulator for fix sessions..the connections  seems working. Can see heart beat and also there is new order sent in logs but simulator doesn't send acknowledgement or don't see that trade in simulator. Can someone help on what could be the issue

**Comment by gbirchmeier** [comment]
No idea what simulator you are talking about.

**Comment by Harryani** [comment]
It's fix session simulator for testing

**Comment by gbirchmeier** [comment]
That means nothing to me.  I don't know what you are using, but if it's not code from this repo, it didn't come from us.
