### ISSUE TITLE
DataDictionary files are missing from nuget

### ISSUE THREAD

**Issue by kirsan31** [connamara/quickfixn#787]
In [docs](https://new.quickfixn.org/n/documentation/#:~:text=Y-,DataDictionary,-XML%20definition%20file):
![image](https://github.com/connamara/quickfixn/assets/17767561/01ca501b-9512-40b5-a71c-e878d10541e2)

These files are missing in nuget packages and in [download](https://new.quickfixn.org/n/download/) sections too.
Can be obtained only from [sources](https://github.com/connamara/quickfixn/tree/master/spec/fix) for now.

P.s. _example applications_ [link](https://new.quickfixn.org/n/documentation/#section-example-applications) in [main page](https://new.quickfixn.org/n/) is not working (the link is correct but click on it doesn't do anything).

**Comment by gbirchmeier** [comment]
It seems that we didn't include the DD files in the previous nuget package release either.  The language on the website actually reflects our zip releases, which do include the DDs.

I'm not sure if it's critical to have them in nuget, but we the docs/site should be much clearer about where to get the default DDs from.  I will work on that before 1.12.

**Comment by gbirchmeier** [comment]
I've added them, they will be in 1.11.1, which I'm trying to put out soon

**Comment by gbirchmeier** [comment]
The PR is #799
