### ISSUE TITLE
Sequence reset on logon

### ISSUE THREAD

**Issue by TomasVetrovsky** [connamara/quickfixn#80]
Part of code has been lost from the C++ version of QuickFix in the Session.NextLogon function. The missing part should handle ResetSeqNumFlag(141) in the received logon message. I am not able to force resynchronization of communication as it was possible with the C++ version of the engine. The missing part goes:

    if (state_.ReceivedReset)
    {
        this.Log.OnEvent("Logon contains ResetSeqNumFlag=Y, reseting sequence numbers to 1");
        if (!state_.SentReset)
            state_.Reset();
    }

It also seems that .Net version is very strict in response to Logon with sequence reset. When I added the code above to overcome "Sequence to low" disconnection, the .Net version of engine responds with logon message with sequence reset flag on. It is handled with the code in GenerateLogon:

    if (state_.ReceivedReset)
        logon.SetField(new Fields.ResetSeqNumFlag(true));

IMHO this behaviour is not needed. As both sides already reset the sequence numbers when they processed the first logon message.

Test (A=Acceptor, I=Initiator):

1. Start communication in a common way. Send some messages to achieve both sequence numbers higher values.
2. Disconnect
3. I - reset session (set seq numbers to zero)
4. I - try connect with ResetSeqNumFlag=Y
5. A - disconnects with "sequence too low" - should connect with reset sequence numbers.

**Comment by gbirchmeier** [comment]
The first bug in the initial report (*disconnect when 141=Y received after disconnect*) was fixed by PR #256 and has been in master for more than a year now.  I just wrote and merged a new acceptance test to verify this bug and the fix.

I'm working on tests/fix for the second bug (*141=Y should not be in the Acceptor's login response*) right now.
