### ISSUE TITLE
In Logout session, the field=553(Username) is redundant

### ISSUE THREAD

**Issue by e70123456** [connamara/quickfixn#818]
When Logout，a response is sent by server to the client, is not Logout  (MsgType(35)=5) message，but rather  Reject  (MsgType(35)=3).
 The error details in the field 'Text (#58)' is "58=Tag not defined for this message type, field=553".

**Comment by e70123456** [comment]
When Logout，a response is sent by server to the client, is not Logout (MsgType(35)=5) message，but rather Reject (MsgType(35)=3).
The error details in the field 'Text (https://github.com/connamara/quickfixn/issues/58)' is "58=Tag not defined for this message type, field=553".

**Comment by e70123456** [comment]
This situation occurs in QuickFix FIX44 1.11.2 version

**Comment by gbirchmeier** [comment]
This is not a bug.  This is an error message.

The server is saying: "Hey client, you sent me a message that contains a 553, but this message is not supposed to contain 553."

If you need more help, please ask your question StackOverflow or the mailing list.
