### ISSUE TITLE
Not send Missing Application messages to the receiving application as response for Resend Request 

### ISSUE THREAD

**Issue by ShaheenHabash** [connamara/quickfixn#825]
the engine was sent a set of Application messages (D,F,G) to the market then he recognize that "connection was forcibly closed by the remote host"
and he try to connect again and once he login the market send "Got resend request from 1795 to 0" 
the engine did not send the missing message to the market and just send "Sent SequenceReset TO: 1826"
please find the logs in the attachment also the .ini file 
[FixEngineLog.log](https://github.com/connamara/quickfixn/files/14098896/FixEngineLog.log)
![image](https://github.com/connamara/quickfixn/assets/20930296/b708d1d7-b5eb-4837-8839-1a73e10cb71a)

**Comment by ShaheenHabash** [comment]
I found in ToApp Function that I was check "possDupFlag" if true I do not send it.

**Comment by gbirchmeier** [comment]
I'm glad you figured it out!

If you need more help, I highly recommend joining the mailing list: http://quickfixn.org/help/
