### ISSUE TITLE
Unhandled Exception in SocketInitiator.OnStart() can Terminate Process

### ISSUE THREAD

**Issue by Falcz** [connamara/quickfixn#833]
We ran into a case of our process terminating due to unhandled exception on a dedicated thread:
```
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at QuickFix.AbstractInitiator.Connect()
   at QuickFix.Transport.SocketInitiator.OnStart()
```

I suspect the `sessionId` coming in from `disconnected` isn't being found during `LookupSession`, but I haven't managed to catch it in the act.

**Comment by Falcz** [comment]
#834 doesn't solve the root cause, but it does provide a layer of protection for application from current/future exceptions that occur in the loop.

**Comment by gbirchmeier** [comment]
Did you see this exception when running 1.11.2?

I've done a lot of work in the past month updating files to use proper nullable (`?`) annotations, and in the process fixing places where vars might be null.  (I see your fix is applied to my more-recent version of the file, with my changes in it.)

However, I haven't finished nullable-izing all the classes yet, so I'm not surprised that the null-risk is still present.

The try/catch is a good step for now.  I'll add it in.  If you are able to get a full stacktrace on the null, please let me know.

**Comment by Falcz** [comment]
We ran into the issue while running 11.0.0.

Nice, I'll keep an eye out for the changes!

I'll fix up the missing `session`, that's what I get for not using an IDE

**Comment by gbirchmeier** [comment]
I'll get it on my branch.  It ties into that other issue I'm working on anyway.  Thanks

**Comment by Falcz** [comment]
Just saw your comment regarding the logger on PR. Sounds good, thanks!

**Comment by Falcz** [comment]
Awesome, thanks!

**Comment by gbirchmeier** [comment]
Hey @Falcz , I'm putting out 1.12 right now.

Do you want to send me your name for our published "Contributors" list?   See the bottom of [this page](https://quickfixengine.org/n/).  All I know is your github handle and your email address.
