### ISSUE TITLE
Wrong time format for TimeStampPrecision=NANO

### ISSUE THREAD

**Issue by MichalUssuri** [connamara/quickfixn#842]
When the QuickFix is configured to use time precision Nano, the output message format is incorrect because it does not produce exactly 9 digits under the seconds. 
The format needs to be changed from "{0:yyyyMMdd-HH:mm:ss}.{1}" to "{0:yyyyMMdd-HH:mm:ss}.{1:000000000}".

Configuration:
TimeStampPrecision=NANO

The problem is with the format definition in the DateTimeConverter class.

**Comment by gbirchmeier** [comment]
I think you may be on to something, but your issue as described is frustratingly thin, and your PR has no Unit Tests.

* Can you provide some concrete examples that observably demonstrate the bug?
* Can you create or update an existing Unit Test that fails under the current implementation, and passes after your fix is made?

**Comment by omtslug** [comment]
related #468

**Comment by gbirchmeier** [comment]
FYI, I wrote a basic unit test in 02b1ed0 that illustrates the issue.  It is an example of what I'd hope to see in future PR submissions such as this one.

That commit is part of PR #850, but I rewrote those tests in a subsequent commit in that PR.  You can see coverage of this situation in `DateTimeConverterTests.cs`: `ToFIXTest()` and `ToFIXTimeOnlyTest()`.
