### ISSUE TITLE
Weekdays setting implementation

### ISSUE THREAD

**Issue by MichalUssuri** [connamara/quickfixn#844]
There is a missing the implementation of Weekdays setting, which is described in 
https://www.quickfixj.org/usermanual/2.3.0/usage/configuration.html

We need to be able to configure the QuickFix to use daily sessions but only on specified days, e.g.:
Weekdays=Mon,Tue,Wed,Thu,Fri

**Comment by MichalUssuri** [comment]
Implementation is in the PR: https://github.com/connamara/quickfixn/pull/845

**Comment by gbirchmeier** [comment]
@MichalUssuri -- please check the contributors list to make sure that I've used the name you want me to use: https://quickfixengine.org/n/
