### ISSUE TITLE
performance tests

### ISSUE THREAD

**Issue by oeresundsgruppen** [connamara/quickfixn#849]
Does anyone have a performance toolset for verifying c# quickfix performance - e.g. various versions, various implementations, e.g. QuickFix.Net versus QuickFIXn, wrappers to QuickFix C++ 1.15.1 ? versus 1.14.x etc.

**Comment by gbirchmeier** [comment]
We have actually had some recent conversations internally at Connamara about doing just that, but not sure if/when that will materialize into action.  It's always hard to prioritize unpaid work.

I'm going to closing this issue because it's not a bug, but feel free to continue any discussion here.

**Comment by oeresundsgruppen** [comment]
not easy for you to know if your changes impacts performance, seem crucial for you to add tests for this
