### ISSUE TITLE
Possible release of 1.10.1 for .net standard users with deadlock fix released as part of 1.11.0

### ISSUE THREAD

**Issue by hariptr162** [connamara/quickfixn#857]
We have a legacy application which is developed using .NET framework 4.8. We have been using QuickFIX/n library 1.10.0 which is the last supported version for .net standard. We have been facing an issue with deadlocks, which is fixed in 1.11.0 ((patch) #647 - replace lock with memory barrier to avoid deadlocks (brunobelmondo)). We would like to get this applied to our application. We can't use 1.11.0 as the support for .net standard removed. Can you please release a patch version 1.10.11 with deadlock fix?

**Comment by gbirchmeier** [comment]
I'm not going to publish a new Nuget package for such a patch, but it should be pretty easy for you to git-checkout tag v1.10.0 in this repo and apply this one-line patch, then build new dlls to use in your project.

Let me know if you need advice for doing that.

I'm going to close this issue, but feel free to reply in the comments.
