### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by oeresundsgruppen** [connamara/quickfixn#874]
Would it be possible to configure enable measurements across quickfix - we can make PR on this, e.g. to measure 

MessageBuilder.Build()

where msgStr is deserialized to Message.

With configuration, it can be disabled by default.

Let me know if we can add PR on this.

**Comment by gbirchmeier** [comment]
I don't know enough about this, but I'm open to taking a look.  Feel free to submit a PR.

(If it'll be a huge PR, maybe you can post a comment describing what it will look like, before implementing the whole thing.)
