### ISSUE TITLE
Duplicate values with different names

### ISSUE THREAD

**Issue by gkotian** [connamara/quickfixn#878]
I'm not sure if this is a bug or if it's intentional, but it seemed strange to me so I thought I'd raise this issue.

[This line](https://github.com/connamara/quickfixn/blob/6e127e6da92f2e2dfd263b4a0c925d5e4c2a9abf/QuickFIXn/Fields/Fields.cs#L1282) and [this one](https://github.com/connamara/quickfixn/blob/6e127e6da92f2e2dfd263b4a0c925d5e4c2a9abf/QuickFIXn/Fields/Fields.cs#L1289) have the same value `'A'`, but the latter one has a weird typo EXXMPT.

In the same class, the values of `UNDISCLOSED` and `D` are also identical, i.e. `'7'`. Not sure if that'll cause issues.

Apologies if this is totally expected and normal (and if there are similar occurrences in other classes). I'm neither familiar with QuickFIX/N nor the FIX protocol itself. I simply happened to stumble across this.

**Comment by gbirchmeier** [comment]
Oh-- I'll add that your other concern (UNDISCLOSED and D both being '7') are technically ok.  It just means that devs can use either symbol to get "7".

But... now I see that FIX41 and FIX42 should probably not be using "D".  I'm not sure if those DDs used to have "D", but now they appear to have "UNDISCLOSED" like the rest.  So I'll make that change too.
