### ISSUE TITLE
Request for New Release with .NET 8 Support

### ISSUE THREAD

**Issue by shukebeta** [connamara/quickfixn#883]
Hi QuickFIX/n Team,

Thank you for your hard work on this wonderful project. It helps us a lot.

I recently noticed that support for older versions of .NET will end on 12th November 2024. Continuing to use unsupported versions of .NET exposes us to security vulnerabilities, and could compromise the integrity of our systems. 

I wish we could have a new release soon that supports .NET8, thank you!

**Comment by gbirchmeier** [comment]
Oh, I did not realize that date was coming.  (I need to pay more attention to the .NET support schedule!)

Yes, the next release should and will be bumped up to .NET 8.  (Actually have a submission about this that I'm finally getting around to.)

**Comment by shukebeta** [comment]
Heads up! .NET 6 support is wrapping up in 8 days.

**Comment by gbirchmeier** [comment]
Argh, I'll see what I can do.
