### ISSUE TITLE
Cannot Connect to ICE. 

### ISSUE THREAD

**Issue by hirenjpatel** [connamara/quickfixn#897]
Hello,

I cannot cannot to ICE using the .net version of QuickFix. ICE is rejecting the connection because of potential TLS issues. It works fine if i connect via stunnel. Do you know if anyone is using QuickFix/n to connect to ICE? Are there any recommentations?

This is the error message i get:

Session FIX.4.4:200012->ICE disconnecting: System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at QuickFix.SocketInitiatorThread.ReadSome(Byte[] buffer, Int32 timeoutMilliseconds)

Thanks,
Hiren Patel

**Comment by gbirchmeier** [comment]
If Stunnel works, I'd say stick with that.

QF/n's SSL support was a contribution, and I must confess that I don't understand the whole topic as well as I wish I did.

To persue it further, I'd suggest asking on StackOverflow and/or [the QF/n mailing list](https://quickfixengine.org/n/support/)
