### ISSUE TITLE
Feature Request: Inquiry about QuickFixN Support for Xetra ETI Protocol

### ISSUE THREAD

**Issue by zpetrovski** [connamara/quickfixn#906]
Dear Connamara Team,

We are currently exploring the possibility of utilizing QuickFixN to connect to the Xetra exchange via their ETI (Enhanced Trading Interface) protocol. As you may know, ETI is a proprietary, high-speed trading protocol designed for performance-critical applications, and it leverages FIX semantics for its message structure and communication.

We would like to understand if the current implementation of QuickFixN is capable of supporting the ETI protocol out of the box. If not, could you advise on the feasibility of tailoring QuickFixN to accommodate the ETI requirements?

Additionally, if there are alternative solutions or approaches that you recommend for implementing ETI connectivity using QuickFixN, we would greatly appreciate your guidance.

Thank you for your time and support. We look forward to your insights.

Best regards,
Zharko

**Comment by gbirchmeier** [comment]
ETI is not FIX.  Its message structures borrow a lot from FIX, but the protocol itself is not FIX, and therefore QF/n will not work.

However, QuickFIX/n's sponsor (and my employer), [Connamara](http://connamara.com) has experience working with the ETI protocol.  We are a custom software consultancy that has much experience building trading systems and market adapters.

If you would like to talk further about how Connamara would be able to help you, I can put you in touch with the right person.  Please let me know!  (you can email me privately at `gbirchmeier@connamara.com`)

(I'm going to close this issue as it is not an actionable QF/n work item, but feel free to keep replying.)

**Comment by zpetrovski** [comment]
Hi Grant,

Thanks for the quick response and for clarifying the capabilities of QuickFIX/n regarding ETI. 
We’re still in the research phase and exploring different options for implementing ETI connectivity. We’ll definitely keep your proposal in mind and may reach out if we decide to move forward with this approach.

Appreciate your help!
